### ISSUE TITLE
Shop unusable in live session

### ISSUE THREAD

**Issue by jbicha** [pop-os/shop#10]
Pop!_OS Beta (build 27)

Open Pop!_Shop
The categories are empty.

See related Ubuntu bug https://launchpad.net/bugs/1718158

**Comment by cassidyjames** [comment]
This is known upstream at https://github.com/elementary/appcenter/issues/1, with a possible workaround being tracked at https://github.com/elementary/appcenter/issues/62

**Comment by brs17** [comment]
In Pop!_OS 18.04, the categories are filled upon opening the Pop!_Shop in a live session.
