### ISSUE TITLE
Pop!_Shop wont show updates available if the Steam repository is added / Steam is installed from the official site

### ISSUE THREAD

**Issue by alosarjos** [pop-os/shop#110]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-shop:
  Instalados: 0.2.9~1543260272~18.10~ded150c
  Candidato:  0.2.9~1543260272~18.10~ded150c
  Tabla de versión:
 *** 0.2.9~1543260272~18.10~ded150c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Pop!_Shop wont show updates when the official Valve-Steam repository is enabled

**Steps to reproduce (if you know):**
1. Install Steam using the .deb provided by the official site (That should add the official repository to the system)
2. Check for updates using terminal
If there are updates:
3. Open the Pop!_Shop, it wont show updates available

**Expected behavior:**
There should be updates available on the Pop!_Shop

**Other Notes:**
Using the Pop!_Shop settings, into the additional repositories, if I disable the steam ones (Binary and Source Code) the Pop!_Shop will work nicely again. If re-enabling them it fails again

**Comment by jsj1027** [comment]
Using I'm using pop-os 19.04 and steam is available through the pop-shop. Is that not the case in 18.10?

**Comment by ChrisgammaDE** [comment]
I have added the spotify ppa and this seems to be the same behavior

```
#/etc/os-release
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```
