### ISSUE TITLE
Misleading translation error in Pop!_Shop (german)

### ISSUE THREAD

**Issue by Anfauglith** [pop-os/shop#114]
**Distribution (run `cat /etc/os-release`):**

```
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
  Installiert:           3.0.1~1549562153~18.10~f4927c0
  Installationskandidat: 3.0.1~1549562153~18.10~f4927c0
  Versionstabelle:
 *** 3.0.1~1549562153~18.10~f4927c0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
The Pop!_Shop shows a very misleading german translation on all "Install" buttons. In german it shows "Installiert", which means "Installed", instead of "Installieren", which would be the correct translation.

**Steps to reproduce (if you know):**
Open the Pop!_Shop, navigate to an Application that is not yet installed. Scratch your head looking at the strange "Install" button that looks as if you already installed the app.

**Expected behavior:**

All "Install"-Buttons in the Pop!_Shop showing the correct german translation for the term "Install", which is "Installieren"

**Other Notes:**

**Comment by brs17** [comment]
@Anfauglith translations are currently held upstream in Elementary's appcenter: https://github.com/elementary/appcenter/

I believe translations are accepted here: https://l10n.elementary.io/projects/appcenter/

**Comment by cassidyjames** [comment]
I see the correct translation here: https://weblate.elementary.io/translate/appcenter/appcenter/de/?checksum=3c030f432aa8f1e2

Is it possible the translations are not pointing to the correct strings in the Pop! fork, causing mismatched translations or something?

**Comment by Anfauglith** [comment]
Thanks @cassidyjames for pointing me to the strings, I was able to pin down the faulty line. For some reason the translation file is not up to date in comparison to elementary upstream.

**Comment by Anfauglith** [comment]
My pull request changing the specific translation was denied, because it will get nuked anyhow when you update. I checked the files again, and it seems that upstream updated almost all translations a month ago, so it would be great if you guys could pull those changes for the next version of pop!_store!

**Comment by mmstick** [comment]
I will create a pair of merge requests today.

**Comment by mmstick** [comment]
Translation merge request was merged just now, so there will be an update soon.
