### ISSUE TITLE
Unusual icon next to search bar

### ISSUE THREAD

**Issue by jbicha** [pop-os/shop#12]
Pop!_OS 17.10 Beta (build 27)

Sometimes, there is an unusual looking icon to the left of the search box in the headerbar of Pop!_Shop.

I'm guessing it's a "something is happening in the background" indicator but it's difficult to understand that's what it means.  The icon isn't clickable and it doesn't have a tooltip.

**Comment by cassidyjames** [comment]
This is just a standard GTK loading spinner. I've filed the issue with the icon set at https://github.com/system76/pop-icon-theme/issues/15

**Comment by cassidyjames** [comment]
Ah I re-read your report. The tooltip is an open issue upstream at https://github.com/elementary/appcenter/issues/394, and I agree that would make it more clear (combined with a better icon)

**Comment by jacobgkau** [comment]
Upstream https://github.com/elementary/appcenter/issues/394 was closed as completed in September 2022, and that commit was included in the recent 7.3.0 rebase.
