### ISSUE TITLE
error trying to overwrite /lib/udev/rules.d/71-nvidia.rules

### ISSUE THREAD

**Issue by omac777** [pop-os/shop#121]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
nvidia-340

**Issue/Bug Description:**
While installing update for driver nvidia-340
I got this error 
Dialog displays in the title io.elementary.appcenter
Error while installing package: trying to overwrite '/lib/udev/rules.d/71-nvidia.rules', which is also in package nvidia-kernel-common-418 418.56-0pop0~1553121653~18.10~82fab6d

**Steps to reproduce (if you know):**
1)installed popos
2)apt-get update
3)apt-get upgrade
3)went into shop and there was an update for driver nvidia-340. clicked the install button and the above error displayed.

**Expected behavior:**
no error after installing nvidia-340 update

**Other Notes:**

**Comment by omac777** [comment]
To resolve the issue, I opened up a terminal
```
sudo bash
mv /lib/udev/rules.d/71-nvidia.rules /home/davidm/
apt-get upgrade -f
apt autoremove
sync

```
The "apt autoremove" removed the nvidia-kernel-common-418 package.

Finally, I clicked the install button for the nvidia-340.170 package and it installed the package successfully.

**Comment by omac777** [comment]
Is there an equivalent to "apt autoremove" with the popos shop gui?

**Comment by mmstick** [comment]
This may cause conflicts if you manually remove files which packages expect to exist.

If you need to downgrade from the 418 driver to the 340 legacy driver, you should fully uninstall the 418 driver first, and then install the 340 driver. You also should not install the 340 driver unless required by legacy hardware.

**Comment by omac777** [comment]
The old bios-based Dell 7500 was the issue.  I was gifted with an hpz workstation with a uefi based system with a newer graphics card that was correctly identified with popos.  everything works now.No disk hangs at install when partitioning either. Rather than taking 30mins to install, it took 5 mins.

Oh the importance of having decent hardware should be emphasized.  Time is so precious.

Thank you.
    On Tuesday, April 9, 2019, 5:01:01 p.m. EDT, Michael Murphy <notifications@github.com> wrote:  
 
 
This may cause conflicts if you manually remove files which packages expect to exist.

If you need to downgrade from the 418 driver to the 340 legacy driver, you should fully uninstall the 418 driver first, and then install the 340 driver. You also should not install the 340 driver unless required by legacy hardware.

**Comment by jacobgkau** [comment]
This sounds like an old NVIDIA packaging issue and/or a support request. I'm going to close this for now, but feel free to comment if this shows up on Pop!_Shop version 7.3.0+ and we'll take another look.
