### ISSUE TITLE
Pop Shop && apt-get won't update

### ISSUE THREAD

**Issue by JonathanAaron** [pop-os/shop#130]

**Comment by brs17** [comment]
@JonathanAaron What version of Pop!_OS are you using? You say `apt-get` won't update. What commands are you using exactly?

**Comment by jacobgkau** [comment]
This sounds like a misplaced support request, and no additional information was provided when requested, so I'm closing this.

Feel free to visit the Mattermost chat room at https://chat.pop-os.org for assistance, or open a support ticket at https://support.system76.com if you're a hardware customer.
