### ISSUE TITLE
Pop!_Picks are cut off

### ISSUE THREAD

**Issue by RickAndTired** [pop-os/shop#133]
**Distribution (run `cat /etc/os-release`):**
 
 Pop!_OS 18.04 LTS
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pop-shop 3.0.1 1567620601 18.04 80ebe02

**Issue/Bug Description:**

Pop!_Picks section is cut off and cannot be viewed

**Steps to reproduce (if you know):**

Start pop-shop

**Expected behavior:**

Viewable Pop!_Picks

**Other Notes:**
These screenshots were taken after starting pop-shop at different times. I cannot scroll up on any one to view more. Multiple themes were tried - Pop, Pop-dark, and Adwaita-dark
Adwaita-dark
![Screenshot from 2019-09-30 12-34-22](https://user-images.githubusercontent.com/53553229/65910514-b8a9d380-e37f-11e9-81c6-7134187c2aa2.png)
Adwaita-dark
![Screenshot from 2019-09-30 12-35-28](https://user-images.githubusercontent.com/53553229/65910516-b9426a00-e37f-11e9-94a1-70daa148fa78.png)
Pop
![Screenshot from 2019-09-30 13-07-42](https://user-images.githubusercontent.com/53553229/65912631-5ce14980-e383-11e9-98c2-40518140d091.png)
Pop-dark
![Screenshot from 2019-09-30 13-09-29](https://user-images.githubusercontent.com/53553229/65912746-931ec900-e383-11e9-9223-caef9d05ae39.png)

**Work Around**
Resizing the window will fix the issue
Focusing on another window will fix the issue. (clicking on any other open program)

**Comment by jacobgkau** [comment]
The picks have been reimplemented since this issue was opened, and I haven't seen them fail to display on recent versions. If anyone sees this again on Pop!_OS 22.04+ with Pop!_Shop 7.3.0+, please leave a comment and we'll reopen the issue.
