### ISSUE TITLE
Icons in Pop!_Shop are Adwaita themed

### ISSUE THREAD

**Issue by brs17** [pop-os/shop#134]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)- Pop!_OS 19.04
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) - 3.24.8-1ubuntu1
 * Desktop environment - GNOME

**Related Application and/or Shell theming (or name of widget)**
Pop!_Shop

**Actual issue**
The icons shown in Pop!_Shop are those of the upstream theme which is different than this icon theme. 

This negatively impacts the association one has between an icon and the application.

**Comment by cassidyjames** [comment]
Afaik we're not doing anything special for this; it's likely in the AppStream data being supplied.
