### ISSUE TITLE
19.10: Certain categories have transparent backgrounds and look strange when highlighted

### ISSUE THREAD

**Issue by leviport** [pop-os/shop#135]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
system76@pop-os:~$ sudo apt update
[sudo] password for system76: 
Get:1 http://us.archive.ubuntu.com/ubuntu eoan InRelease [255 kB]
Hit:2 http://apt.pop-os.org/proprietary eoan InRelease                         
Hit:3 http://ppa.launchpad.net/system76/pop/ubuntu eoan InRelease              
Hit:4 http://us.archive.ubuntu.com/ubuntu eoan-security InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease
Get:7 http://us.archive.ubuntu.com/ubuntu eoan/universe Sources [9,696 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu eoan/universe i386 Packages [8,705 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages [8,816 kB]
Fetched 27.5 MB in 20s (1,350 kB/s)                                            
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

**Issue/Bug Description:**
When the Accessories, Graphics, and Office application categories are highlighted, the backgrounds appear transparent and are difficult to read when highlighted.
![pop-shop-transparent-category](https://user-images.githubusercontent.com/13512097/66845916-2c2a1400-ef2e-11e9-9bdf-13aef3491404.png)

**Steps to reproduce (if you know):**
They can be highlighted by clicking them, then clicking the "Home" (back) button. When you return to the home screen, the button will be highlighted.

**Expected behavior:**
Here is a screenshot of the same behavior in 19.04:
![pop-shop-transparent-category-1904](https://user-images.githubusercontent.com/13512097/66846125-8a56f700-ef2e-11e9-8513-ec05447a18ad.png)

**Other Notes:**

**Comment by brs17** [comment]
This happens with both the light and dark theme.
