### ISSUE TITLE
Sync Pop_Shop with AppCenter Upstream

### ISSUE THREAD

**Issue by brs17** [pop-os/shop#144]

**Comment by mmstick** [comment]
This is currently done in the `pop-rebase_eoan` branch

**Comment by brs17** [comment]
> This is currently done in the `pop-rebase_eoan` branch

Is there any reason we should not create the pr (with the understanding that we don't want to merge it until all of the other flatpak support is read as well)?

**Comment by mmstick** [comment]
I can create the PR, but it cannot be merged since it is a rebase

**Comment by pedrofleck** [comment]
It's a bit off-topic, but how can I upgrade to pop-rebase_eoan from pop-rebase? I'm on 19.10.

**Comment by mmstick** [comment]
`_eoan` branches are exclusively only available to 19.10, so you already have it if you've added the `pop-rebase` repo.

**Comment by pedrofleck** [comment]
Oh, ok then, thanks, and sorry about the off-topic.

**Comment by brs17** [comment]
Closing, as this has been done in 20.04
