### ISSUE TITLE
App hangs when looking at the details page for an installed app

### ISSUE THREAD

**Issue by jbicha** [pop-os/shop#15]
Pop!_OS 17.10 Beta (build 27)

Open Pop!_Shop to look at the details page of an installed app. The app will stop responding.

I wasn't able to reproduce this bug by looking at the details page for an app that wasn't installed.

**Comment by cassidyjames** [comment]
I can't seem to reproduce this for either type of app, but I've seen it reported upstream at https://github.com/elementary/appcenter/issues/334. I think this is the same issue.

**Comment by jbicha** [comment]
I am using VirtualBox. The 2 apps I tested were with GNOME Calendar and GNOME Tweak Tool (after installing it).

**Comment by cassidyjames** [comment]
@jbicha thanks for the further details. I try and take a look to see if I can reproduce it.

**Comment by mmstick** [comment]
This was fixed by #91
