### ISSUE TITLE
Cancel button is too close to the progress bar when the shop is opened with another window

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/shop#160]
**Distribution (run `cat /etc/os-release`):**
 
 aaronh@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

aaronh@pop-os:~$ apt policy pop-shop
pop-shop:
  Installed: 3.1.1pop0~1584569025~20.04~4ec99e1
  Candidate: 3.1.1pop0~1584569025~20.04~4ec99e1
  Version table:
 *** 3.1.1pop0~1584569025~20.04~4ec99e1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

![close-up](https://user-images.githubusercontent.com/4884946/77238183-b3da1580-6b93-11ea-9241-fa63a128ea97.png)
![two-windows](https://user-images.githubusercontent.com/4884946/77238187-b6d50600-6b93-11ea-8853-552ac086d7b4.png)

**Steps to reproduce (if you know):**

Open two windows with Pop Shell enabled and one of them needs to be the Pop!_Shop then install an application.

**Expected behavior:**

The Cancel button it a few pixels lower from the progress bar.

**Comment by isantop** [comment]
Should be fixed as of 6700e26 as such:

![Screenshot from 2020-03-23 13-21-34](https://user-images.githubusercontent.com/5883565/77354952-46e88c00-6d09-11ea-9fc4-e5a2b3e6519b.png)
