### ISSUE TITLE
Some pages don't shrink enough

### ISSUE THREAD

**Issue by isantop** [pop-os/shop#163]
If I tile it to be a quarter of the width of my 1920x1080p display, only some pages shrink down to that width. The other video, "quarter-width-1920x1080.mp4" shows this. It's still usable at that width, but it does overlap with other windows on the right edge. It's still heaps better than some other default apps though, so I'm not sure how good is good enough, at least for the present moment.

[pop-shop-videos.zip](https://github.com/pop-os/shop/files/4331132/pop-shop-videos.zip)

_Originally posted by @leviport in https://github.com/pop-os/shop/pull/156#issuecomment-598867134_

**Comment by isantop** [comment]
@leviport I can't seem to replicate the problem where the pop-shop homepage doesn't shrink down enough for the window to get that narrow. Do you know if there are some replication instructions that will better indicate why that's happening?

**Comment by leviport** [comment]
I'll try to get something more reproducible. It's kind of a hit-or-miss thing that happens if I'm dragging the width from side to side.

**Comment by leviport** [comment]
Give this a try
1. Open Pop!_Shop
2. Click on Builder
3. Drag the window wide enough to show 2 columns of categories back on the home page
4. Go back to the home page
5. Try to resize narrower. For me it gets stuck at a minimum of 2 columns of categories wide, and refuses to re-stack to one column wide.
4. Click 
![Screenshot from 2020-03-23 14-04-19](https://user-images.githubusercontent.com/13512097/77358298-36d3ab00-6d0f-11ea-862c-500c7a21c0eb.png)

**Comment by isantop** [comment]
@leviport I see what's causing that. It's the extra window controls. Does the problem go away if you turn those off?

**Comment by leviport** [comment]
Good catch -- I can confirm that turning off minimize and maximize buttons allows it to shrink properly. I wonder if we could detect the presence of the extra controls and account for them. What do you think?

**Comment by WatchMkr** [comment]
We're going to try to solve these cases by resizing the fork to match the minimum size. https://github.com/pop-os/shell/issues/85
