### ISSUE TITLE
Version of signal available is expired (1.29.6)

### ISSUE THREAD

**Issue by ExperimentsWithCode** [pop-os/shop#169]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Had installed signal via pop shop awhile ago and just received a notice its expired. Tried to upgrade through pop shop, but no upgrade is available. Uninstalled, but see the version I had is the current one offered in the shop. 

**Steps to reproduce (if you know):**
Just have it app open.

**Expected behavior:**
Non expired version available

**Other Notes:**
https://github.com/signalapp/Signal-Desktop/releases

**Comment by Oymate** [comment]
Yeah had to manually install :/

**Comment by WatchMkr** [comment]
Please consider updating to Pop!_OS 20.04. Flatpak has been introduced in 20.04 which will help keep Signal and other packages up-to-date.
