### ISSUE TITLE
Peek's app page has strange styling

### ISSUE THREAD

**Issue by leviport** [pop-os/shop#170]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 20.04

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
 ```
pop-shop:
  Installed: 3.1.1pop0~1585158386~20.04~cafc28e
  Candidate: 3.1.1pop0~1585158386~20.04~cafc28e
  Version table:
 *** 3.1.1pop0~1585158386~20.04~cafc28e 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Peek's header styling turns the dropdown and install button orange:
![peek](https://user-images.githubusercontent.com/13512097/79790997-d766bc00-8309-11ea-86e6-8f904a8c5462.png)

**Steps to reproduce (if you know):**

**Expected behavior:**
Most applications look more like this:
![tilix](https://user-images.githubusercontent.com/13512097/79791057-eb122280-8309-11ea-875c-b86c385b5c81.png)

**Other Notes:**

**Comment by cassidyjames** [comment]
The AppData you're shipping for Peek (and a handful of other apps) includes brand colors, which AppCenter is designed to use for the header.

**Comment by leviport** [comment]
Ah that explains it. Thanks @cassidyjames !
