### ISSUE TITLE
Hard code Pop!_Picks in Pop!_Shop

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shop#177]
To improve speed and allow different definitions per release

New Pop!_Picks list

Atom
Slack
Telegram
Meld
Steam
Lutris
Mattermost
Code
Spotify
Tilix
Alacritty
Peek
Virtual Manager
Signal
Flameshot
Postman
DBeaver
Chrome

**Comment by jackpot51** [comment]
Is this required for 20.04 release?

**Comment by cassidyjames** [comment]
I'm wondering if we could make this easier upstream by supporting hardcoded picks for the different API endpoints. One advantage this could give us upstream is in caching the previous picks, i.e. for offline use.
