### ISSUE TITLE
20.04: Only 14 of 18 Pop!_Picks appear

### ISSUE THREAD

**Issue by leviport** [pop-os/shop#180]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
pop-shop:
  Installed: 3.1.1pop0~1588107614~20.04~695cb7b
  Candidate: 3.1.1pop0~1588107614~20.04~695cb7b
  Version table:
 *** 3.1.1pop0~1588107614~20.04~695cb7b 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
I'm only seeing 14 out of the 18 Pop!_Picks on the main screen
![14picks](https://user-images.githubusercontent.com/13512097/80644637-31acfe80-8a27-11ea-937f-d4af39a920df.png)

**Steps to reproduce (if you know):**
Launch and behold!

**Expected behavior:**
All picks should appear

**Other Notes:**

**Comment by brs17** [comment]
I seem to be back to all 18. Check again?

**Comment by leviport** [comment]
Adder is down to 13 now and my darter is down to 2.

**Comment by jackpot51** [comment]
Did you install any? They disappear when installed

**Comment by leviport** [comment]
Ah, that was probably it then. I was testing all of them, so the ones that remained probably had multiple sources. Sorry about that.
