### ISSUE TITLE
Can't find the .deb version of various apps

### ISSUE THREAD

**Issue by BootlegPhil** [pop-os/shop#185]
I can't find the .deb versions of Steam or GiMP in the Shop, just the Flatpak ones. And when I install ed the .deb versions of Steam and GiMP through the Terminal, the Shop did not recognize that they were installed.

Are there any plans to remedy this?

**Comment by WatchMkr** [comment]
This should now be fixed. Open Pop!_Shop and give Pop!_Picks a moment to load on the Home screen. You'll see the latest version of the Pop!_OS Steam debian package there.
