### ISSUE TITLE
"no description available" multiple times as heading

### ISSUE THREAD

**Issue by WuerfelDev** [pop-os/shop#189]
**Distribution (run `cat /etc/os-release`):**
 Pop!OS 20.04 LTS
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
It shows "no description available" multiple times and that looks like a heading
![Screenshot from 2020-05-13 14-21-47](https://user-images.githubusercontent.com/12686819/81812714-ce42c680-9526-11ea-8a7d-4d61ac1606bf.png)

**Steps to reproduce (if you know):**

**Expected behavior:**
Show packages that can be updated without these "headings" inbetween

**Other Notes:**

**Comment by jacobgkau** [comment]
Descriptions no longer seem to be formatted this way in current versions (checked on 7.3.0):

![image](https://github.com/pop-os/shop/assets/7199422/64284773-6f5b-4459-845e-7e77b8f7925a)

Please leave another comment if you see this again.
