### ISSUE TITLE
Add support for back button

### ISSUE THREAD

**Issue by isantop** [pop-os/shop#19]
Some Mice/Keyboards offer a back button (e.g. for going back in the browser and file managers, etc.). This should be supported in Pop_Shop too, since we have a generic back button action. Should be as simple as looking for that signal and tying it to the back button.

**Comment by cassidyjames** [comment]
Dupe of upstream bug https://github.com/elementary/appcenter/issues/23, not sure if we want to leave this one open or not.

**Comment by isantop** [comment]
We should leave it open until the upstream bug is closed.
