### ISSUE TITLE
Pop Shop makes extremely loud noise when there is no more character before the backspace.

### ISSUE THREAD

**Issue by Oymate** [pop-os/shop#192]

**Comment by Oymate** [comment]
Probably related to GNOME.

**Comment by cassidyjames** [comment]
Yeah, this is a standard behavior in GTK entry widgets. It can be disabled system-wide, though I forget how exactly in GNOME.

**Comment by Oymate** [comment]
@cassidyjames Sorry for pinging, but can you remember the way to disable it? :)

**Comment by cassidyjames** [comment]
It looks like you can control its volume (or mute it) in _Settings_ → _Sound_ → _Volume Levels_ → _System Sounds_.

![Screenshot from 2020-05-29 21-37-44](https://user-images.githubusercontent.com/611168/83318777-2fd88580-a1f5-11ea-9a74-c6bbba3bd9a8.png)
