### ISSUE TITLE
Can't find the .deb version of GiMP

### ISSUE THREAD

**Issue by BootlegPhil** [pop-os/shop#197]
I can't find the .deb version of GiMP in the Shop, but I can see the Flatpak one. When I installed the .deb version of GiMP through the Terminal, the Shop does not recognize that it is installed.

I was previously able to see all of this in the Shop.

**Comment by A-Random-Lantern** [comment]
I heard that this was done on purpose, pretty sure their reasoning was because the flatpak was more up to date.

**Comment by mmstick** [comment]
The GIMP deb packages stopped carrying appstream data a year or two ago. So it's normal that GIMP isn't appearing in the shop, because the shop only shows applications that have appstream data.
