### ISSUE TITLE
Krita problems

### ISSUE THREAD

**Issue by BootlegPhil** [pop-os/shop#200]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-shop:
  Installed: 3.3.0pop0~1589405854~20.04~72b0ae9
  Candidate: 3.3.0pop0~1589405854~20.04~72b0ae9
  Version table:
 *** 3.3.0pop0~1589405854~20.04~72b0ae9 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

The version of Krita on the store doesn't support languages other than American English. However, the krita-l10n package seems to be the current version of Krita, and it has all the languages. I recommend listing this on the store.

**Steps to reproduce (if you know):**

Install Krita from the store and go to the language changing option.

**Expected behavior:**

For the program to support languages other than American English.

**Comment by leviport** [comment]
Thanks for the report! Is this true for both the .deb version of Krita and the flathub version of Krita?

**Comment by BootlegPhil** [comment]
> Thanks for the report! Is this true for both the .deb version of Krita and the flathub version of Krita?

I made a mistake. l10n is just a translation package, not another version of Krita. When installing it and the .deb version of Krita, language selection seems to work fine now. And the version of Krita on the shop isn't 4.3, so I made a mistake in telling you that it was the latest one.
