### ISSUE TITLE
Pycharm Flatpak Stuck on 3.7 env

### ISSUE THREAD

**Issue by dasgeekchannel** [pop-os/shop#202]
**Distribution (run `cat /etc/os-release`):**
Version 20.04 LTS
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pycharm Community and Pycharm Professional

**Issue/Bug Description:**
Flatpak version of Pycharm is stuck in a 3.7 environment when the Pop!_OS version is 3.8. Trying to utilize Tkinter or any system oriented packages in conjunction with Pycharm Flatpak edition generates errors. Issues w/ interpreter in the Flatpak version. Resolution is to install Pycharm from Pycharm website; however official website version does not incorporate itself into Application menu without manual intervention. Error received when running a python file that imports tkinter is that it ModuleNotFound Error despite being installed on the system.

**Steps to reproduce (if you know):**
Try any Python file in Flatpak Pycharm version that imports Tkinter. 

**Expected behavior:**
Would be expected once you install Tkinter or other similar system tools in Pop!_OS that Flatpak would have access to them and latest 3.8 version of Python for interpretation. Flatpak does not operate the same as the full application. Expectation is that it would. 

**Other Notes:**
I'm not an expert in Python but a student. This issue caused me hours of frustration trying to get Flatpak and Snap version of Pycharm working. I would imagine others who are utilizing the beautiful Pop!_OS for learning Python and using Pycharm would be equally frustrated. Perhaps there is a workaround but I could not find one. It would be better in my opinion to remove the Flatpak version entirely or if there is a workaround to provide some instructions during install to get it to use the current version of Python and have access to correct path for GUI tools, etc. or last option and preferred would be to install the non universal package version of Pycharm instead.

Here is this issue reported by someone else: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008194399-PyCharm-2020-1-Flatpak-Install-on-Pop-OS-20-04-not-seeing-the-new-python3-8-interpreter-

**Comment by Zooce** [comment]
What version of PyCharm are you seeing in Pop Shop? I ask because I saw an odd version issue with Bitwarden, and after some digging, found that the URL for Flathub used in Pop Shop was different than the one in the quick setup on Flathub. After updating the URL to match the one shown by Flathub (https://flatpak.org/setup/Pop!_OS/), it had the latest version of Bitwarden.
Old URL: https://dl.flathub.org/repo/
New URL: https://flathub.org/repo/
Might be unrelated, but figured I'd at least mention it...

**Comment by mmstick** [comment]
Any issues with flatpak packages should be brought up on their flathub repositories.
