### ISSUE TITLE
Pop Shop Feature Request

### ISSUE THREAD

**Issue by TC68** [pop-os/shop#205]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 Currently, the Pop Shop lists a range of software, but does not include all items available in the repositories. For example, inkscape tutorials (apt install inkscape-tutorials) and the libreoffice styles. I understand keeping the main listing clean and categorised without all the odds and ends, but these items do not even show up when searched for, and are not listed as extras at bottom of application pages either (an aspect of the pop-shop which is not obvious).

My request is to enable Pop Shop to be able to list all available packages (perhaps on a separate tab or something), and for all available packages to be able to appear and be installed if searched for directly.

For example, if I enter "inkscape" in the search field of Pop Shop I get the deb and flatpak versions of inkscape listed, as well as LyX. However, if I search the apt cache directly, many more items are available:

tim@Trinity:$ apt-cache search inkscape
create-resources - shared resources for use by creative applications
dpic - pic-language converter to LaTeX-compatible and other formats
fonts-opendin - Open DIN font
fonts-rufscript - handwriting-based font for Latin characters
ink-generator - Inkscape extension to automatically generate files from a template
inkscape - vector-based drawing program
inkscape-open-symbols - Open source SVG symbol sets that can be used as Inkscape symbols
inkscape-speleo - Inkscape plugin to help draw surveys
inkscape-survex-export - Inkscape plugin to digitise printed surveys
inkscape-tutorials - vector-based drawing program - tutorials
lyx - document processor
python3-scour - SVG scrubber and optimizer (Python 3 module)
python3-sphinxcontrib.svg2pdfconverter - Sphinx SVG to PDF Converter Extension
robocut - Control program for Graphtec cutting plotters
scour - SVG scrubber and optimizer (CLI and debhelper)
texlive-lang-english - TeX Live: US and UK English
tim@Trinity:$ 

If I search pop-shop for "libreoffice-style" (say, to find a set of icons/theme to work with dark mode) there is a long list of apps, mostly unrelated to libreoffice and none of them being the libreoffice styles. Searching the apt cache gives a much more focussed result:

tim@Trinity:$ apt-cache search libreoffice-style
libreoffice-style-breeze - office productivity suite -- Breeze symbol style
libreoffice-style-colibre - office productivity suite -- colibre symbol style
libreoffice-style-elementary - office productivity suite -- Elementary symbol style
libreoffice-style-tango - office productivity suite -- Tango symbol style
libgtkspellmm-3.0-0v5 - C++ wrapper library for GtkSpell (shared libraries)
libgtkspellmm-3.0-dev - C++ wrapper library for GtkSpell (development files)
libgtkspellmm-3.0-doc - C++ wrappers for GtkSpell (documentation)
libreoffice-style-galaxy - transitional package for Galaxy symbol style
libreoffice-style-hicontrast - transitional package for Hicontrast symbol style
libreoffice-style-human - transitional package for Human symbol style
libreoffice-style-karasa-jaga - office productivity suite -- Karasa Jaga symbol style
libreoffice-style-oxygen - transitional package for Oxygen symbol style
libreoffice-style-sifr - office productivity suite -- Sifr symbol style
tim@Trinity:$

**Comment by cassidyjames** [comment]
Pop!_Shop is based on elementary AppCenter, and AppCenter at least is committed to using FreeDesktop standards like AppStream to populate packages. Ideally, those packages would include valid AppData of their own so they would be made available to all package managers like GNOME Software, AppCenter, Pop!_Shop, KDE Discover, etc.

**Comment by TC68** [comment]
So would be the best way to kick this along to raise it as a bug for the elementary App Center, or to leave this bug here for  the Pop!_OS maintainers? Or both?

**Comment by cassidyjames** [comment]
You can leave it here for Pop!_OS folks to respond, but the point is that AppCenter or Pop!_Shop don't have control over those packages. They just show packages that provide AppData, and it's up to the packages (or the source repository) to include that data.

**Comment by TC68** [comment]
Thanks

**Comment by mmstick** [comment]
If you need this, I'd recommend using Synaptic, since the appcenter is designed for appstream packages only
