### ISSUE TITLE
nvidia-driver-440-server is offered in Installed tab

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shop#211]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** `3.3.0pop0~1596119648~20.04~c095d00`

**Issue/Bug Description:** `nvidia-driver-440-server` is showing up under the Drivers section of the Installed tab in the Pop!_Shop. There is an "Install" button next to it, but it is not installable due to a dependency issue.

**Steps to reproduce (if you know):**
1. Perform a fresh install of Pop!_OS 20.04 on an NVIDIA machine
2. Install all updates and reboot
3. Open the Pop!_Shop

**Expected behavior:** `nvidia-driver-440-server` should not be offered.

**Other Notes:** I see that when https://github.com/pop-os/shop/pull/206 was made to fix this, we were seeing 418-server (and it stopped showing up after the fix), so perhaps 440-server was later added and is now matching the int check?

**Comment by mmstick** [comment]
Integer parsing should always return `0` when the string being parsed is not a number. Something's up here
