### ISSUE TITLE
nvidia-driver-450 is offered in Installed tab

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shop#219]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04 LTS 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** `3.3.0pop0~1599666445~20.04~889726a`

**Issue/Bug Description:** `nvidia-driver-450` (version 450.66) is being offered in the Installed tab, even though we [did not release that version](https://github.com/pop-os/nvidia-graphics-drivers/pull/56). Attempting to install it results in a dependency error.

**Steps to reproduce (if you know):** Open the Pop!_Shop on an NVIDIA machine.

**Expected behavior:** Newer versions than we are currently shipping should not show up as available in the Drivers section.

**Other Notes:**

![nvidia-450-66-screenshot](https://user-images.githubusercontent.com/7199422/93908230-a117d900-fcbb-11ea-82fc-1df32d88b9d8.png)

![nvidia-2](https://user-images.githubusercontent.com/7199422/93908357-c1479800-fcbb-11ea-8bf7-5f18bc68f19d.png)

**Comment by jacobgkau** [comment]
On a machine that was out of date, I didn't see `nvidia-driver-450` start showing up until `ubuntu-drivers-common` was updated to `1:0.8.4pop0~1600272756~20.04~5985fd0` (from `1:0.8.1.1pop0~1593714233~20.04~9abb487`).

**Comment by leviport** [comment]
Also seeing this on oryp6 and major-r2 (2080)

**Comment by leviport** [comment]
Fixed by https://github.com/pop-os/shop/pull/220

Fix for future Ubuntu driver appearances is in the works here: https://github.com/pop-os/shop/pull/220
