### ISSUE TITLE
Include Elementary OS repo

### ISSUE THREAD

**Issue by gjsman** [pop-os/shop#22]
I know perfectly well Elementary OS apps aren't really designed for Pop! OS, but it would be nice to have those apps. They probably won't look _too_ bad either.

**Comment by jackpot51** [comment]
This isn't a matter of how they look, but how reliable they will be. Elementary is currently on Ubuntu 16.04 as a base, while we are on Ubuntu 17.10. It is possible a large number of applications will not even run due to conflicting library versions.

**Comment by isantop** [comment]
@gjsman In addition to the compatibility issues mentioned above, AppCenter Apps are designed for elementary. This was the wishes of the elementary team, for most of the same reasons that have already been mentioned.
