### ISSUE TITLE
Pop Shop instability

### ISSUE THREAD

**Issue by GeorgeKitsopoulos** [pop-os/shop#227]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop Shop
3.3.0pop0~1600965555~20.04~f37e26a

**Issue/Bug Description:**

Pop shop is a bit unstable compared to other linux appstores. For example if I click an option too fast there is a high possibility that it will crash. This happens more often when the NVIDIA gpu is active, but it can also happen just with the intel processor alone. The app also crashes sometimes when trying to update apps esspecially flatpaks. Another issue, a very small one, is the fact that while updating apps they dissapear and reapear randomly after a dew seconds. Flatpak packages installed through pop shop wont be able to be updated via terminal, making the updates a slow tedious process. Those problems aren't new I had them since I first tried Pop, but they were less annoying and frequent (18.4LTS - and since then I have reformatted several times - the upgrade was a clean install too). What I am encountering might not be new but it has bugged me for a while and finally has made me write this bug report. Everything else on the system works as expected, its just the appstore that is a bit buggy.

**Steps to reproduce (if you know):**

Clicking installed in the first seconds after opening the store causes some of the crashes. I usually wait for about at least ten seconds. More bugs when NVIDIA driver is active. I don't know how the other bugs can be reproduced, im not even sure if it affects only me because I do not have another pc to test.

**Expected behavior:**

Other times it just does what it is supposed to do (only with the clicking bug not the other ones).

**Other Notes:**

I also have another thing I would like to point out. Is it just me or the Pop shop settings take more than a few seconds to open?
And seriously thank you for this amazing os, you have made gaming on linux amazing!

Specs:
OS: Pop!_OS 20.04 LTS x86_64
Host: Nitro AN515-51 V1.13
Kernel: 5.4.0-7642-generic
Packages: 2808 (dpkg), 31 (flatpak),  
Shell: bash 5.0.17
Resolution: 1920x1080
DE: GNOME
WM: Mutter
WM Theme: Pop
Theme: Sweet-Dark [GTK2/3]
Icons: candy-icons [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i7-7700HQ (8) @ 2.800GHz
GPU: NVIDIA GeForce GTX 1050 Mobile
GPU: Intel HD Graphics 630
Memory: 2860MiB / 7844MiB

**Comment by JeroenGoddijn** [comment]
Same here....and it seems to be getting more unstable... a (relatively) simple app/package store shouldn't take this long too load and/or have this many issues freezing/hanging...

It won't even open...it starts the Pop! Shop...you see the mouse pointer changing into loading circle...but nothing ever opens

**Comment by Hxs2fJKjYZ** [comment]
Same for me too, just recently installed Pop!_OS 20.10 and Pop_shop is constantly freezing up and I'm having to kill the process and re-launch it to install apps.
Pop!_OS without NVIDA drivers was installed.

**Comment by ArjunSingh99** [comment]
Pop shop is extremely laggy for me. It's unusable for me. I have to use the terminal to update my packages, which I don't mind, but kinda voids the point of having a store.
I'm on a laptop with an i5 5200U and a GTX 830m

**Comment by GeorgeKitsopoulos** [comment]
> Pop shop is extremely laggy for me. It's unusable for me. I have to use the terminal to update my packages, which I don't mind, but kinda voids the point of having a store.
> I'm on a laptop with an i5 5200U and a GTX 830m

Can you update flatpaks from the terminal too? I can't, they only get updated from the store for some reason.

**Comment by ArjunSingh99** [comment]
> > Pop shop is extremely laggy for me. It's unusable for me. I have to use the terminal to update my packages, which I don't mind, but kinda voids the point of having a store.
> > I'm on a laptop with an i5 5200U and a GTX 830m
> 
> Can you update flatpaks from the terminal too? I can't, they only get updated from the store for some reason. Edit: also delta updates are non-existent which is a shame.

I just do:
`flatpak update`

I don't know what you mean by delta updates..

**Comment by GeorgeKitsopoulos** [comment]
> > > Pop shop is extremely laggy for me. It's unusable for me. I have to use the terminal to update my packages, which I don't mind, but kinda voids the point of having a store.
> > > I'm on a laptop with an i5 5200U and a GTX 830m
> > 
> > Can you update flatpaks from the terminal too? I can't, they only get updated from the store for some reason. Edit: also delta updates are non-existent which is a shame.
> 
> I just do:
> `flatpak update`
> 
> I don't know what you mean by delta updates..

By delta updates I mean the download and installation of select parts of the app (the updated files not everything. It saves time. I also run flatpak update but it never finds updates via the terminal. That only happens for flatpaks. Snaps and rest update just fine. So when updates are available I can only install them through pop store.

**Comment by GeorgeKitsopoulos** [comment]
Tried again and now I can update flatpaks via terminal. So until the shop is fixed I can avoid it as much as possible.

**Comment by ArjunSingh99** [comment]
There was an update to pop shop, I think it was called "fast appstore" or something. I don't know if it was that particular update or some other update, but my pop shop seems fine for the most part now. Only when I open the pop shop for the first time and it searches for updates, it stutters a little bit, but other than that, it feels a lot better.

**Comment by GeorgeKitsopoulos** [comment]
> There was an update to pop shop, I think it was called "fast appstore" or something. I don't know if it was that particular update or some other update, but my pop shop seems fine for the most part now. Only when I open the pop shop for the first time and it searches for updates, it stutters a little bit, but other than that, it feels a lot better.

Just noticed it with latest update. It feels somewhat snappier now. But I will reserve judgement untill there are a lot of updates especially flatpak ones so I can test it properly.

**Comment by Hxs2fJKjYZ** [comment]
> > There was an update to pop shop, I think it was called "fast appstore" or something. I don't know if it was that particular update or some other update, but my pop shop seems fine for the most part now. Only when I open the pop shop for the first time and it searches for updates, it stutters a little bit, but other than that, it feels a lot better.
> 
> Just noticed it with latest update. It feels somewhat snappier now. But I will reserve judgement untill there are a lot of updates especially flatpak ones so I can test it properly.

I can confirm that the update seems to have solved the issue for me too.

**Comment by rpggeek** [comment]
Same here and the pop-shop command doesn't work for me it says "command not found" if i try to open it from terminal (sorry if i mistake because i'm new to linux).

**Comment by GeorgeKitsopoulos** [comment]
> Same here and the pop-shop command doesn't work for me it says "command not found" if i try to open it from terminal (sorry if i mistake because i'm new to linux).

It is: io.elementary.appcenter
You can see it too on task manager. Basically it is a fork of the elementary store.
