### ISSUE TITLE
Pop!_Shop should provide Run option when searching for a program already installed

### ISSUE THREAD

**Issue by isantop** [pop-os/shop#23]
_From @brs17 on October 18, 2017 16:57_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.
```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS 17.10

**Issue/Bug Description**
Under the "Home" tab, when searching for a program that is already installed on the system, there should be an "Open" button to open the program. 

Currently:
![screenshot from 2017-10-18 10-30-28](https://user-images.githubusercontent.com/7460774/31731617-dd915524-b3f2-11e7-9fa8-bb6835ea98ab.png)

Desired:
![screenshot from 2017-10-18 10-56-20](https://user-images.githubusercontent.com/7460774/31731682-0c19a536-b3f3-11e7-8718-1d948b88d64a.png)

_Copied from original issue: pop-os/iso#173_

**Comment by cassidyjames** [comment]
@brs17 unless I'm misunderstanding something, this is already the case. Some apps can't show an "Open" button because of missing appstream data, though, so that might be what you're seeing here with this specific app.

**Comment by brs17** [comment]
Yeah, I'm honestly not quite sure what I was going for there.
