### ISSUE TITLE
Unexisting updates are reported in Pop Shop

### ISSUE THREAD

**Issue by dodalovic** [pop-os/shop#236]
Latest Pop OS

![image](https://user-images.githubusercontent.com/6358061/99686487-eb32f600-2a83-11eb-8e97-2e42a922b1a2.png)

**Comment by jacobgkau** [comment]
Please be advised https://github.com/pop-os/shell is for the window tiling utility, Pop Shell. If you're not sure where an issue should go, it should be reported in https://github.com/pop-os/pop.

It looks like another user had "seemingly non-existent updates" in the Pop!_Shop, and it was solved by running some Flatpak commands: https://github.com/system76/docs/issues/493 

The commands are:

```
flatpak update
flatpak uninstall --unused
```

Does the update number go away after running those and restarting the Pop!_Shop?

**Comment by dodalovic** [comment]
Sorry that I opened in the wrong repo. Yes, it did go away. 
Hope this workaround will not be needed in the future.

Thanks!

**Comment by jacobgkau** [comment]
I agree that the commands should not need to be run manually. It looks like we have another issue open for this already: https://github.com/pop-os/shop/issues/198
