### ISSUE TITLE
Handle .flatpakref files

### ISSUE THREAD

**Issue by Oymate** [pop-os/shop#239]
If any app comes from the flathub repo, then popshop should handle .flatpakref file and install the app.

**Comment by cassidyjames** [comment]
This is what [Sideload](https://github.com/elementary/sideload) is for, which is designed as a companion to AppCenter (from which Pop!_Shop is forked).

**Comment by Oymate** [comment]
It would be even better if PopShop cancelled this. Since it is natural to assume PopShop is what handles all flatpak packages by default

**Comment by cassidyjames** [comment]
When Sideload is installed, it is a much cleaner and faster experience; for precedent, Pop!_Shop doesn't even contain the code to manage third-party repositories, but it hands that responsibility off to a separate, simpler app. This modularity is part of what makes AppCenter and thus Pop!_Shop faster and simpler than other software centers like GNOME Software.

**Comment by thorhop** [comment]
> When Sideload is installed, it is a much cleaner and faster experience

Can confirm. Just built from master (gh elementary/sideload) and it works alright. The pop up modal opens up under your cursor, which is cool. Also looks okay with the dark theme.. Should be packaged as a deb along with future versions of Pop!_Shop.

![image](https://user-images.githubusercontent.com/1967775/102566519-007d5d80-40e0-11eb-8367-40d50f1b2f08.png)

**Comment by Oymate** [comment]
Another thing to remember then is to make flathub repo part of trusted repo.

**Comment by Gadiguibou** [comment]
+1 since Pop!_OS now includes Flathub by default it would be really nice to have `.flatpakref` support by default without having to compile a program from source! Even including in a Pop ppa would be nice :)

**Comment by mmstick** [comment]
Pop already supports installing them with Sideload

**Comment by adityamwagh** [comment]
How should I install sideload? It it in pop repos? Or is it available as a flatpak?

**Comment by Gadiguibou** [comment]
> How should I install sideload? It it in pop repos? Or is it available as a flatpak?

It's not available in either. As far as I know you have to build it from source.

**Comment by n-hebert** [comment]
This should be re-opened or ported to another PopOS project -- it's surprising to see that a "build from source" is suggested as the solution to a UX hole here. I disagree that installing Sideload is a proper solution, but since it must be built from source, I would say it's not a solution at all.

This is PopOS, after all -- I am using this to work on not to hack on. If I were on my Arch, Gentoo, etc. distro I would expect that answer.
