### ISSUE TITLE
Pop Shop can be launched once. After closing, it will fail to launch until the next restart.

### ISSUE THREAD

**Issue by ghost** [pop-os/shop#243]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-shop:
  Installed: 3.3.0pop0~1607377061~20.04~996e63e
  Candidate: 3.3.0pop0~1607377061~20.04~996e63e
  Version table:
 *** 3.3.0pop0~1607377061~20.04~996e63e 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

The pop shop can be launched once, but after closing, it will not be able to be reopened until a restart or logout.

**Steps to reproduce (if you know):**
The loading spinner runs for a significant amount of time after launching, even after it appears to have finished checking for updates. If the program is closed before the spinner has disappeared, it seems to result in being unable to launch the pop shop again until logging out or restarting.

**Expected behavior:**
Pop Shop should be able to launch after being closed.

**Other Notes:**

**Comment by spencersean77** [comment]
After some testing, it seems this may be the result of closing the store before the loading spinner has finished whatever it's doing. It seems to go on spinning for quite some time even after launching and checking for updates. I have closed the store twice now, after making sure the loading spinner has disappeared, and have had successful launches of the store afterwards.

**Comment by jacobgkau** [comment]
On the current version (7.3.0), I'm able to open and close the Pop!_Shop and have it launch again normally, even if it's closed while the metadata refresh is occurring.

This sounds like a support request and the GitHub user has been deleted, so I'm closing this issue. For similar reports, a good troubleshooting step would be running `io.elementary.appcenter` in a terminal and providing the output.
