### ISSUE TITLE
Shows wrong licence for Visual Studio Code

### ISSUE THREAD

**Issue by joeljose350** [pop-os/shop#250]
# Distribution version

NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 

# Description

The Visual Studio Code app in the Pop!_Shop says that it uses a proprietary licence but it is actually using the MIT licence and the source code is available on their [github repo]( https://github.com/microsoft/vscode).

# Steps to reproduce

Open Pop!_Shop and search for Visual Studio Code.
Scroll down to the bottom and look at the licence section at the bottom left corner of the page.

# Expected behavior

The licence section should show MIT Licence instead of Proprietary.

**Comment by cassidyjames** [comment]
As mentioned in the linked GitHub repo's README:

>[Visual Studio Code](https://code.visualstudio.com) is a distribution of the `Code - OSS` repository with Microsoft specific customizations released under a traditional [Microsoft product license](https://code.visualstudio.com/License/).

The Microsoft product license is not considered a free software license as it places additional stipulations on the use and redistribution of the product. Just because some of the source code is open does not mean the whole app as delivered is.

**Comment by bflanagin** [comment]
We are not the package maintainer and have no say in these matters. 

Closing issue, this is neither bug nor feature request.

**Comment by joeljose350** [comment]
Please delete this issue

**Comment by leviport** [comment]
Sure thing
