### ISSUE TITLE
Pop Shop can't search or install PPA packages.

### ISSUE THREAD

**Issue by PolyPaul** [pop-os/shop#256]
**Distribution (run `cat /etc/os-release`):**
 
```
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
```
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Issues with PPA packages in general but tested with Howdy.

```
howdy:
  Installed: 2.6.1
  Candidate: 2.6.1
  Version table:
 *** 2.6.1 500
        500 http://ppa.launchpad.net/boltgolt/howdy/ubuntu groovy/main amd64 Packages
        500 http://ppa.launchpad.net/boltgolt/howdy/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status


```
**Issue/Bug Description:**
Pop Shop cannot install or search for packages added via PPAs.
Synaptic pakcage manager and KDE DIscover seem to handle well.
![Screenshot from 2021-02-08 03-54-34](https://user-images.githubusercontent.com/8498668/107156590-8b812280-69c2-11eb-9afa-7c28002321f1.png)

**Steps to reproduce (if you know):**
Add a PPA.
Reboot or update cache
Search for added package in Pop Shop

**Expected behavior:**
Newy added package should appear

**Other Notes:**
This also seems to be an issue with Gnome-software on Ubuntu. Unsure if this is an issue with Pop or its upstream varient Elementary Software center.

**Comment by leviport** [comment]
Does installing Howdy install a graphical application? Pop!_Shop does not show packages that don't create a .desktop file, while Synaptic does.

**Comment by cassidyjames** [comment]
I suspect this is actually about AppStream data; Pop!_Shop uses the standard AppStream format for application data, but Canonical does not support AppStream data being delivered along with packages in PPAs. As such, apps in PPAs that are not also available in the system repositories will not show up in Pop!_Shop.

**Comment by PolyPaul** [comment]
Yes. This seems to e due to AppStream data. Seems like this is intended or at least, not a bug. CLosing.
