### ISSUE TITLE
Gravit Designer won't install: "Aborted due to failure"

### ISSUE THREAD

**Issue by QuesterLEJ** [pop-os/shop#265]
**Distribution: Pop!_OS 20.10**
 
 

**Issue/Bug Description:** Attempting to install the Flatpak version of Gravit Designer returns an error and the app does not install. The error message indicates that the installation "aborted due to failure." More specifically, it states that "extra data" was the "wrong size": "Aborted due to failure (Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip)"

**Steps to reproduce:** Open Pop! Shop, search for "Gravit Designer," and attempt to install the app.

**Expected behavior:** Gravit Designer should install

**Other Notes:** I'm relatively new to Linux, but it seems to me that the pointer to the correct file in the repository might be wrong. The app is a current one, actively developed, so there shouldn't be a reason it isn't available for installation. As of 14 September 2021, I've updated this report to include the most current wording of the installation error, which is now more specific.

**Comment by jacobgkau** [comment]
Gravit Designer is no longer on Flathub. It looks like Corel (who purchased Gravit in 2018) has replaced it with their Corel Vector web app, as gravit.io now redirects to https://www.coreldraw.com/en/product/vector/.
