### ISSUE TITLE
PopShop interferes with version control, even from external origins

### ISSUE THREAD

**Issue by CaseyNordcliff** [pop-os/shop#276]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
All known versions of the Pop Shop, to the best of my knowledge

**Issue/Bug Description:**
Whenever you install a package from an external source that is listed in the Pop Shop, if their versions don't match, the Pop Shop thinks what is has is the "newer version", even though it isn't.

**Steps to reproduce (if you know):**
I tried this with Atom, the text editor, but it works with any package that meets the following three criteria:
a) Pop Shop has that package listed
b) You can install it from a different source (like a .deb file for example)
c) The .deb file is the newer version

Steps:
1) Download Atom from here: https://github.com/atom/atom/releases (I got 1.57 which is current version at the time of writing)
2) Install the package via this command: sudo dpkg -i <filename>.deb
    2a) optional: verify the version is 1.57
3) Once it's installed, open Pop Shop, and go to the installed software tab.
4) You will notice that Pop Shop thinks it has an update for you, but it actually downgrades you from 1.57 to 1.54 (again, all version numbers are as of the time of writing)

**Expected behavior:**
When Pop Shop gets the version of what you have, compares it against its own, and if what you have is newer, one of the following should happen, either seems reasonable to me:
1) Leave it alone, and assume the user has a more up to date version
2) Run a script to update the Pop Shops database of current version numbers for that package and try again.

**Other Notes:**
If you need more details, or need to get in touch with me, the best way to do so is via the System76 discord channel, where I go by THOR#2586. I'll try and get back to you as quick as I can, but it will usually be the same day.

**Comment by CaseyNordcliff** [comment]
As additional info, running an update command is the terminal is blocked by this issue. In the attached picture, you can see that Firefox needs an update, but is blocked on Atom not being allowed to be "downgraded".

the command "update" on my system is aliased to the following: "sudo apt update && sudo apt upgrade -y && sudo flatpak update && sudo apt full-upgrade"

Had I passed the --allow-downgrades argument, Firefox would have been updated, and Atom downgraded. The only workaround that I have found is going into the Pop Shop and manually clicking the "Update" button next to each package, except Atom.

![Screenshot from 2021-06-28 18-11-53](https://user-images.githubusercontent.com/82059802/123710582-03020200-d83d-11eb-9b31-44533a00a529.png)

**Comment by mmstick** [comment]
The shop does not have any control over picking and choosing versions. That's performed by apt.

**Comment by CaseyNordcliff** [comment]
What would you recommend as a course of action then?
