### ISSUE TITLE
Brave/Chrome not available in Pop Shop

### ISSUE THREAD

**Issue by titojankowski** [pop-os/shop#286]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
n/a

**Issue/Bug Description:**
Brave isn't available in the Pop Shop, nor is Chrome. Would expect they would be there as they're reasonably popular browsers.

**Steps to reproduce (if you know):**
Search for Brave or Chrome on the Pop Shop

**Expected behavior:**
I expect them to be available to install.

**Other Notes:**
Thanks for all that you do to make Pop OS great. I'm not a developer, switching over from Mac, want things to just work.

**Comment by jacobgkau** [comment]
Brave Browser and Google Chrome are both available in the Pop!_Shop now thanks to Flathub.

![image](https://github.com/pop-os/shop/assets/7199422/5d64fbb5-2c94-4212-9b95-d56f6651c20c)

![image](https://github.com/pop-os/shop/assets/7199422/876e73fd-9029-44e0-8f38-f45e98cc6739)
