### ISSUE TITLE
Pop!_Shop thinks it's offline when it isn't

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shop#289]
![image](https://user-images.githubusercontent.com/3430283/133816680-57521e84-222c-4049-8dec-4ef4073c9137.png)

**Comment by jackpot51** [comment]
Related: https://bugs.launchpad.net/ubuntu/+source/packagekit/+bug/1943189

**Comment by jackpot51** [comment]
I believe Ubuntu will have this fixed in the next few days. A fix was attempted but the syntax was not quite right.

**Comment by jackpot51** [comment]
> Probably about a week out for Impish due to the beta freeze, so that should give a timeline.

**Comment by jackpot51** [comment]
:cry:

**Comment by 13r0ck** [comment]
Still waiting on a new 21.10 ISO to see if that fixes the issue

**Comment by leviport** [comment]
Not seeing this on the newest 21.10 isos
