### ISSUE TITLE
With no network connection, "Network Settings" button does not work.

### ISSUE THREAD

**Issue by brs17** [pop-os/shop#29]
When launching the Pop!_Shop without an Internet connection, the following screen is displayed.

![pop _shop_networkconnection](https://user-images.githubusercontent.com/7460774/33284378-27776afa-d36c-11e7-9a99-73d5b0aa4335.png)

Selecting the "Network Settings..." button does not do anything.

I would expect the "Network" or "Wifi" page to open.

**Comment by isantop** [comment]
It's probably trying to open the Network plug in Switchboard

**Comment by brs17** [comment]
Should be fixed with pull request https://github.com/pop-os/shop/pull/35
