### ISSUE TITLE
MInecraft not installing

### ISSUE THREAD

**Issue by BurntRanch** [pop-os/shop#290]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Minecraft, the command just returns Unable to locate package minecraft-launcher

**Issue/Bug Description:**
I Can't install minecraft, it just returns this
Aborted due to failure (While trying to checkout 7898e3822e6f10310c8f2b6ae8aa630ed102eb1e3341c7e57e0aa9757987d2ea into /home/astronautintheocean/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/20.08/.7898e3822e6f10310c8f2b6ae8aa630ed102eb1e3341c7e57e0aa9757987d2ea-C1LY90: Opening content object 16acd107fc91481d04eb267e77b4c815d0dba3dffcfe6b3c54ed6cdd343800a5: Couldn't find file object '16acd107fc91481d04eb267e77b4c815d0dba3dffcfe6b3c54ed6cdd343800a5')

**Steps to reproduce (if you know):**
Do a clean install of pop os NVIDIA, install everything (except the driver) then reboot, and try to install minecraft.

**Expected behavior:**
just install?

**Other Notes:**
nothing

**Comment by rvente** [comment]
How were you trying to install it? Command line or Pop Shop? From the error logs, it looks like it's installing the flatpak version. Perhaps bringing the system up-to-date with `sudo apt update` and `sudo apt upgrade`, then restarting Pop Shop will be a good first troubleshooting step.

**Comment by jacobgkau** [comment]
I'm able to install and run Minecraft from the Pop!_Shop:

![Screenshot from 2023-10-09 11-53-27](https://github.com/pop-os/shop/assets/7199422/0b4eb91b-66ab-4185-a7c8-51abe0ba76b4)

![Screenshot from 2023-10-09 11-53-37](https://github.com/pop-os/shop/assets/7199422/68d15a43-8c51-4784-9ae3-f7cb398b20d6)

This issue is either transient, or has already been fixed on Flathub.
