### ISSUE TITLE
Search Results Loose Back Button

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/shop#300]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
pop-shop:
  Installed: 3.4.2pop0~1634231591~21.10~ee0f962
  Candidate: 3.4.2pop0~1634231591~21.10~ee0f962
  Version table:
 *** 3.4.2pop0~1634231591~21.10~ee0f962 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Back button disappears after clicking on a searched item. The only way to return home is then to clear the search bar

**Steps to reproduce (if you know):**
1. Search for an app
2. Open a search result
3. Click the back button.
![back_disapears](https://user-images.githubusercontent.com/58987761/141163831-662674b4-9903-4f90-a602-c5cf66bd6977.gif)

**Expected behavior:**
Back button should show.

**Other Notes:**

**Comment by cassidyjames** [comment]
Confirmed upstream: https://github.com/elementary/appcenter/issues/1750

**Comment by 13r0ck** [comment]
Now waiting on elementary/appcenter#1752 to be merged and down streamed.
