### ISSUE TITLE
extremely bad performance on searching

### ISSUE THREAD

**Issue by protodrew** [pop-os/shop#319]
**Distribution (run `cat /etc/os-release`):**
 
 Pop OS 21.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

3.4.2pop0~1638820932~21.10~fcc9028

**Issue/Bug Description:**

Pop-shop crashes 50-60% of the time when searching something, the rest of the time it's very sluggish
I have tested this on numerous installations of pop os and have had this problem since at least 19.10.

**Steps to reproduce (if you know):**

search for something on pop os (crashed for me on spreadsheet and syncthing, but has done for numerous other things)

**Expected behavior:**

searches execute quickly and smoothly

**Other Notes:**

This is genuinely a huge issue that will turn off a lot of non-techy new Linux users. If maintaining the pop shop isn't going to become more sustainable and improve over time, it's probably the time to just move back to the elementary app center or gnome software with flatpaks instead of snaps. Not trying to belittle the hard work that the pop-shop contributors have put in, but we need the app store to get more attention rather than the neglect it feels like it has received.

**Comment by 610th** [comment]
The search is not just slow, but also bad. For example, the query `VSCodium` will find the correct app but not the query `codium`.

**Comment by protodrew** [comment]
I would just like to say that performance for me has improved drasticly on the latest version of the Pop-shop distributed for apt. Will close this for now but if someone else is experiencing plz open.
