### ISSUE TITLE
Installed Apps not being showed

### ISSUE THREAD

**Issue by winuxue** [pop-os/shop#32]
I have downloaded some apps (Opera, Skype, Visual Studio Code), etc from their official website and installed using Eddy.
The problem is that these apps are not being showed in the Shop/Updates Tab, so i'm unable to uninstall them.
Is strange, because updates for some of these apps are being listed, but the applications are not being showed. so i cannot click in the application to uninstall it

**Comment by btkostner** [comment]
I'm going to guess this is because they do not ship appstream data

**Comment by isantop** [comment]
You'll need to manage manually installed applications through Eddy or the command line.
