### ISSUE TITLE
[Bug Report] Pop!_Shop showing a menu for choosing a different type of package format for applications which only have 1 package format

### ISSUE THREAD

**Issue by Random-Person213** [pop-os/shop#324]
**Distribution (run `cat /etc/os-release`):**
 
 Pop!_OS 21.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

The Pop!_Shop (latest version)

**Issue/Bug Description:**

When there are some apps which are only offered as a deb or only offered as a flatpak package, the Pop!_Shop has a clickable menu to change the package format, but that is useless because there's no other option other than the one already chosen, like if the package is only flatpak and there's no deb version of it (and vice versa), that menu is useless.

**Steps to reproduce (if you know):**

1. Open the Pop!_Shop
2. Go to an app which only offers a flatpak version or only offers a deb version (an example is the "signal" application, it only offers a flatpak version)
3. You should have an arrow next to the "flathub (flatpak)" (or it will say it's a deb package if you choose a deb only application) thing which tells you the package format of the app, and if you click it, you have a menu which only shows the same option which was already chosen.

**Expected behavior:**

The Pop!_Shop shouldn't have a menu for choosing a package format for an application which only has 1 type of package format.

**Screenshots:**
![image](https://user-images.githubusercontent.com/78260512/151686573-1d6c19fc-61ed-4e87-b34e-d52150108bc1.png)

**Comment by jacobgkau** [comment]
I'm not seeing the drop-down for that app on the latest Pop!_Shop version (7.3.0):

![Screenshot from 2023-10-09 11-58-13](https://github.com/pop-os/shop/assets/7199422/525ebdc0-6aab-47e1-a3e5-9ebb307ce358)

Please let us know if you see another app that this is still happening with.
