### ISSUE TITLE
Needs a lot more optimization

### ISSUE THREAD

**Issue by cobalt2727** [pop-os/shop#325]
**Distribution (run `cat /etc/os-release`):**
 Pop OS 21.10, but this has been the case ever since I installed back on... either 20.04 or 20.10, I don't remember which. It definitely applies to both of those anyway.
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```bash
pop-shop:
  Installed: 3.4.2pop0~1638820932~21.10~fcc9028
  Candidate: 3.4.2pop0~1638820932~21.10~fcc9028
  Version table:
 *** 3.4.2pop0~1638820932~21.10~fcc9028 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
The Pop!_Shop is consistently the one process using the most RAM on my setup - even compared to individual Chrome processes. This would be fine if it wasn't running in the background constantly, too. Every time I open the system monitor, this is what's **always** at the top:
![image](https://user-images.githubusercontent.com/60624944/151706972-6635c02d-52af-4234-8e6d-26e16857af81.png)

It would be nice if we could replace the store with `gnome-software`, as that's much lighter on the system and is more performant, too (see https://github.com/pop-os/shop/issues/319 for an example of what I'm talking about, I experience this every time I open it, and I'm on an i5-7200U so it's definitely not a question of hardware power).
Unfortunately, this hasn't been possible on Pop!_OS for as long as I've used it:
```bash
cobalt@cobalt-inspiron:~$ sudo apt install --no-install-recommends gnome-software gnome-software-plugin-flatpak 
[sudo] password for cobalt: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Depends: sessioninstaller but it is not installable
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```
I guess I *could* try installing Plasma Discover and hoping it works with my theme well...

**Steps to reproduce (if you know):**
open Pop OS without having uninstalled `pop-shop` via apt and/or killed its process in the `System Monitor`

**Expected behavior:**
_not_ having the software store taking up almost half a gig of my RAM without me even using it

EDIT: this has been the case since 20.04 https://github.com/pop-os/shop/issues/257

**Comment by leviport** [comment]
The rebase is expected to help: https://github.com/pop-os/shop/pull/311

**Comment by cobalt2727** [comment]
Seems like that did the trick - though fixing the `gnome-software` incompatibility would still be nice...

**Comment by cobalt2727** [comment]
Reopening this issue - that seems like it definitely had a major impact, but it's still close to using as much RAM as the desktop environment itself. I understand I'm kind of nitpicking here, but I usually install stuff from the terminal and this screenshot was taken without me ever having opened the store itself since powering on the computer.

![image](https://user-images.githubusercontent.com/60624944/152995169-9be3f396-d4c3-4b65-a568-123762811bd9.png)

**Comment by cobalt2727** [comment]
It's happening again - I haven't opened the Pop Shop in the foreground at all.

![image](https://user-images.githubusercontent.com/60624944/155755545-7801a8d1-bb9c-480d-8526-5cbdebf28964.png)

**Comment by cobalt2727** [comment]
It keeps happening, so I know this isn't a one-off. I've been checking the system monitor every time I see a notification saying an update is available.
![image](https://user-images.githubusercontent.com/60624944/155891763-7852c466-acdf-4d4e-8de7-561b0430272d.png)

**Comment by cobalt2727** [comment]
More documentation showing this is a consistent issue:
![image](https://user-images.githubusercontent.com/60624944/156858903-0e848114-ddda-49eb-90e1-72dd2b6f65ed.png)

**Comment by cobalt2727** [comment]
_Still_ manages to be way higher than the DE itself and Discord.

![image](https://user-images.githubusercontent.com/60624944/158170734-3ca081a0-fbc4-47b5-b116-7eda6a915e42.png)

**Comment by mmstick** [comment]
There's no point in commenting every week. That said, this is a downstream to https://github.com/elementary/appcenter so when they fix it, it'll be fixed here.

**Comment by cobalt2727** [comment]
Sounds good. The `gnome-software` incompatibility apparently [got fixed](https://github.com/pop-os/desktop/pull/78) recently, so I'll close this.
