### ISSUE TITLE
Interface Improvement Suggestion: make the back button look like one

### ISSUE THREAD

**Issue by l0k18** [pop-os/shop#334]
![Screenshot from 2022-03-07 07-34-46](https://user-images.githubusercontent.com/20619963/156974326-bfbaf5f4-1330-4d8e-9365-5aaf05acc95f.png)

As you can see in the top left, there is a mysterious button appearing after one clicks on a search result item or from 'installed' page.

It is entirely unclear by this where this goes, or that it is even a button. I hovered over it to highlight it in the screenshot.

It is, in fact, a back button, that goes to the previous page. 

I am simply suggesting, put a 'back' arrow on it or 'back to', and perhaps consider further clarification of the navigation in the HeaderBar. 

I am a big fan of HeaderBars (and android and iOS use them, that's where the idea came from, afaik) but they don't work if the meaning of the buttons, and the fact of them being buttons, is not clear to the user.

**Comment by cassidyjames** [comment]
This looks to be a stylehseet issue; previous versions of the Pop! stylesheet had a `←` arrow inside the button, which has a `.back-button` class.

**Comment by l0k18** [comment]
I should also verify ... I'm running current Pop OS 21

**Comment by leviport** [comment]
Can you share which themes you have enabled? It looks non-default to me, and I see an arrow in the default Pop theme:
![2022-03-09_09-09](https://user-images.githubusercontent.com/13512097/157481766-19f3761b-3d55-4f79-97d7-e95b1d06c8a2.png)

**Comment by l0k18** [comment]
Oh, I didn't think of that... Yes orchis dark compact is the name of my theme. Obviously it's the cause of the bug. I will close this as you have identified the cause.
