### ISSUE TITLE
Auto update certain apps like web browsers 

### ISSUE THREAD

**Issue by RasheedAZ** [pop-os/shop#335]
Hi guys. I've searched in the issues and haven't found a matching result.

I need to update the web browsers to automatically update on our school PCs without any user intervention. Is that possible with with Pop Shop?

We're using Pop!_OS 21.10 and we need Firefox and Brave to update in the evening...

I've seen that Elementary Appcenter already has a toggle for auto update so could something like that be introduced in Pop Shop?

Thanks.

**Comment by mmstick** [comment]
No, but you can try pop-system-updater or write a script to install.

**Comment by senntore** [comment]
I thought something similar to auto update was being implemented in https://github.com/pop-os/upgrade/pull/225

**Comment by RasheedAZ** [comment]
> I thought something similar to auto update was being implemented in [pop-os/upgrade#225](https://github.com/pop-os/upgrade/pull/225)

That's great news - I thought I'd have to install the snap versions of the browsers. Hopefully it gets released soon. I guess I can wait a bit. 

In the meantime, what do you guys think about scheduling updates to certain flatpak packages using cron jobs? Good idea or not? 

Something like this:

`0 * * * * flatpak update -y org.mozilla.firefox org.mozilla.Thunderbird org.chromium.Chromium io.gitlab.librewolf-community`

**Comment by mmstick** [comment]
> I thought something similar to auto update was being implemented in [pop-os/upgrade#225](https://github.com/pop-os/upgrade/pull/225)

This is GUI integration for the pop-system-updater service.
