### ISSUE TITLE
[22.04] Crashing due to unresolvable apt dependencies

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shop#341]
**Distribution (run `cat /etc/os-release`):** 22.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** 2100231 (master) and 7116406 (upstream-rebase)

**Issue/Bug Description:** This morning, `gnome-remote-desktop` is being held back for some reason, and apt thinks that `gnome-control-center` is not satisfying a dependency for `pop-desktop`. These issues would probably be separate from the Pop!_Shop.

However, rather than displaying an error dialogue, the Pop!_Shop is segfaulting. This is near the end of the terminal output:

```
(io** (io.elementary.appcenter:8809): WARNING **: 09:25:48.076: Package.vala:567: Operation failed for package Operating System Updates - The following packages have unmet dependencies:
  pop-desktop: Depends: gnome-control-center but it is not installable
               Recommends: io.elementary.sideload but it is not installable


(io.elementary.appcenter:8809): GLib-GObject-CRITICAL **: 09:25:48.078: g_value_get_pointer: assertion 'G_VALUE_HOLDS_POINTER (value)' failed
Segmentation fault (core dumped)
```

**Steps to reproduce (if you know):** Open the Pop!_Shop on a 22.04 system and try to install/upgrade packages.

**Expected behavior:** No crash should occur and an error dialogue should appear if the operation is not successful.

**Other Notes:** Not caused by or fixed by the upstream-rebase branch.

**Comment by GabrielDougherty** [comment]
I had the same problem today after upgrading to 22.04. Here's the full output:
https://gist.github.com/GabrielDougherty/682a844da5b12dba872c51b2851262fe

**Comment by GabrielDougherty** [comment]
I just built pop shop from source on latest commit https://github.com/pop-os/shop/commit/b2e7dbbb0594705dd6a3ab8b07925372de4da543 and ran with `./src/io.elementary.appcenter`. Then I clicked Update All (this used to segfault). The update completed successfully.

**Comment by GabrielDougherty** [comment]
@smolattack Try System76 support: https://support.system76.com/

**Comment by mdbiscan** [comment]
I have several machines using pop. Only one had this issue. I tried upgrading in the terminal with apt instead, but discovered it was an issue with dpkg not being configured. I ran the following commands:

```sudo dpkg --configure -a```

and then 

```sudo apt --fix-broken install```

After this, I was able to upgrade packages in the terminal with apt. It's possible that Pop Shot would also be able to update after doing these commands.

**Comment by TS-CUBED** [comment]
Pop-Shop seems to crash whenever there is any kind of problem with the repos, or when there are held/pinned packages.

Expected behaviour: show the error message to the user, rather than just silently failing/crashing the app

**Comment by michaelboeyens** [comment]
> I have several machines using pop. Only one had this issue. I tried upgrading in the terminal with apt instead, but discovered it was an issue with dpkg not being configured. I ran the following commands:
> 
> `sudo dpkg --configure -a`
> 
> and then
> 
> `sudo apt --fix-broken install`
> 
> After this, I was able to upgrade packages in the terminal with apt. It's possible that Pop Shop would also be able to update after doing these commands.

Worked for me. Thanks!

**Comment by gladiatorgiftson** [comment]
Yeah i can confirm this pop os crashes occasionally it seems to be of pop shop
