### ISSUE TITLE
Segmentation fault when attempting to uninstall VIM (ubuntu-minimal dependency)

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/shop#353]
**Distribution (run `cat /etc/os-release`):**
 
 22.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

VIM (text editor)

**Issue/Bug Description:**

PopShop unexpectedly terminates if you try to uninstall.

**Steps to reproduce (if you know):**

Open PopShop. Go to Installed. Scroll down until you see VIM. Click Uninstall. In the middle of the process, PopShop just closes.

**Expected behavior:**

(Obvious)

**Other Notes:**

**Comment by jacobgkau** [comment]
I wonder if this could be related to https://github.com/pop-os/shop/issues/341; it seems the shop is crashing in situations where it should be displaying an error message about apt dependencies.

**Comment by prophet6250** [comment]
> I wonder if this could be related to #341; it seems the shop is crashing in situations where it should be displaying an error message about apt dependencies.

I think we should blame Linus Tech Tips for this move from System76 xD
Instead of helping the user out and letting them know what's wrong, just shut the app down and prevent the user from doing anything remotely dangerous. Treading on Apple like behavior right here...

**Comment by merriam** [comment]
Adding to what @prophet6250 commented, the sudden shut down is  a bit chilling.

I ran across this trying to uninstall the preinstalled `IBus Table`, an input driver which may or may not be required by Gnome.  As I don't work with east asian languages, I wanted to uninstall it and PopShop promptly crashed.
