### ISSUE TITLE
GSConnect does not launch even clicked open buttom from pop-os shop

### ISSUE THREAD

**Issue by khewweifeng** [pop-os/shop#366]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 22.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-shell-extension-gsconnect

**Issue/Bug Description:**
GS Connect does not launch even clicked open buttom from pop-os shop

**Steps to reproduce (if you know):**
Install GSConnect via pop-os store

**Expected behavior:**

**Other Notes:**

**Comment by n3m0-22** [comment]
I was able to replicate this issue. Try the following.

1. `sudo apt install gnome-shell-extension-gsconnect`
2. restart GNOME shell with `Alt`+`F2` type `r` and then `Enter` 
3. Open Extensions and make sure GSConnect is enabled.

Once enabled it should now show up in your quick settings menu just below WiFi.

**Comment by n3m0-22** [comment]
After further testing it seems GNOME shell just needs to be restarted, or the machine rebooted before the GSConnect extension becomes enabled and shows up in the quick settings menu. After that it is set to enabled without further user interaction, and is working properly. I'm closing this issue, but I can always reopen it if you are still having problems.
