### ISSUE TITLE
Bad Repository error message doesn't offer a button to open software sources to correc the problem

### ISSUE THREAD

**Issue by isantop** [pop-os/shop#37]
_From @MarkoPetteri on December 20, 2017 15:34_

**Reporter info**

Newbie user with a newbie problem. If this is the wrong place to post problems like this, please redirect me. I already posted to reddit about this too.

Pop!_OS 17.10 64-bit | GNOME 3.26.2 | AMD Ryzen 5 1400 Quad-Core Processor × 8 | 7,8 GB RAM | 25 GB SSD + 120 GB SSD | GeForce GT 630/PCIe/SSE2 | Focusrite Scarlett 2i2

 * Related Application

Pop!_Shop

**Issue/Bug Description**

When I open Pop!_Shop! this message starts popping up and stacking up. If I use another workspace it pops up there. I can't use Pop!_Shop if I don't close them all. I can't close Pop!_Shop through the tab next to Activities. Also I cannot find one of the pop up messages and so cannot close them all.

I could get around this by rebooting or killing it through the terminal but I think this is not a behaviour we're looking for. Hence the post.

Here's the contents of the message:
" io.elementary.appcenter

Failed to Fetch Updates

E: The repository 'http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu artful Release' does not have a Release file. W: Updating from such a repository can't be done securely, and is therefore disabled by default. W: See apt-secure(8) manpage for repository creation and user configuration details "

**Steps to reproduce**

Launch Pop!_Shop.

_Copied from original issue: pop-os/iso#197_

**Comment by isantop** [comment]
@MarkoPetteri Thanks for opening an issue! It looks like that issue is being caused that repo you attempted to add. Removing the errant entry in the `Software & Updates` application will fix the problem. In the meantime, I'm going to work on adding a button to the dialog to open software sources directly so that problems from this can be fixed easier.

**Comment by MarkoPetteri** [comment]
Ah, I didn't realize there's an app for that, so I installed Synaptic to do it. I'm used to repository stuff being in the same app as "the shop".

The problem continued for one instance of Pop!_Shop after I deleted the ppa. That time it was about all the other ppa's (default ppa's). But after I closed that instance, the problem hasn't repeated.

**Comment by brs17** [comment]
Sounds like we're all happy here. Closing!
