### ISSUE TITLE
Searching directly without clicking on the search bar

### ISSUE THREAD

**Issue by realKarthikNair** [pop-os/shop#375]
**Distribution (run `cat /etc/os-release`):**
 
    NAME="Pop!_OS"
    VERSION="22.04 LTS"
    ID=pop
    ID_LIKE="ubuntu debian"
    PRETTY_NAME="Pop!_OS 22.04 LTS"
    VERSION_ID="22.04"
    HOME_URL="https://pop.system76.com"
    SUPPORT_URL="https://support.system76.com"
    BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
    PRIVACY_POLICY_URL="https://system76.com/privacy"
    VERSION_CODENAME=jammy
    UBUNTU_CODENAME=jammy
    LOGO=distributor-logo-pop-os

 **Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

    io.elementary.appcenter

**Issue/Bug Description:**

Earlier I could open pop shop and directly type in whatever I want to search  
But since a few days, I need to click the search bar in Pop Shop before searching anythng

**Steps to reproduce (if you know):**

1. Open Pop Shop
2. Type in search string
3. Nothing happens (unless I go and click the search bar)

**Expected behavior:**

1. Open Pop Shop
2. Type in search string
3. Package search success

**Other Notes:**

If this was an intentional 'update',  I personally feel this more like a downgrade and I'm sure I'm not alone

**Comment by ArikRahman** [comment]
+1 Issue happens to me as well. Also, when I click on, say, Slack, for instance, or any app, it disallows searching. I have to go back to the home page to search, even though the search bar is visible on an app page.

**Comment by realKarthikNair** [comment]
Thank you guys
