### ISSUE TITLE
pop!_shop exits on it own sometimes without giving any error message

### ISSUE THREAD

**Issue by akhlaq-choudhary** [pop-os/shop#381]
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 

**Issue/Bug Description:**
when i  open pop stop it load some second and exit its own and doesn't give any error 

**Steps to reproduce (if you know):**
when you open pop shop and go to some category it loads some second and exit on its own and it doesn't even give any error message

**Expected behavior:**
its shouldn't exist on it own

**Comment by leviport** [comment]
The next time you see this happen, can you collect the output from a manual upgrade from the terminal and post it here? The upgrade command is this: `sudo apt update && sudo apt upgrade`

**Comment by NukeManDan** [comment]
Also have this, with some updates outstanding so says the shop, try to update, and it crashes, no logs.

Related: https://www.reddit.com/r/pop_os/comments/wewrnj/the_following_packages_have_been_kept_back_in/
Using a mirror for ubuntu as a backup & redundancy (omitting some hits):
```
sudo apt update && sudo apt upgrade
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:6 http://apt.pop-os.org/proprietary jammy InRelease
Hit:9 http://apt.pop-os.org/release jammy InRelease
Hit:10 https://lug.mines.edu/mirrors/ubuntu jammy InRelease
Hit:11 http://apt.pop-os.org/ubuntu jammy InRelease
Hit:12 https://lug.mines.edu/mirrors/ubuntu jammy-security InRelease
Hit:13 http://apt.pop-os.org/ubuntu jammy-security InRelease
Hit:14 https://lug.mines.edu/mirrors/ubuntu jammy-updates InRelease
Hit:15 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Hit:16 https://lug.mines.edu/mirrors/ubuntu jammy-backports InRelease
Hit:17 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://prerelease.keybase.io/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  cuda cuda-11-7 cuda-drivers cuda-drivers-515 cuda-runtime-11-7
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
```

How can I view logs of the pop shop app? I can't find it in the apps list on flatpak, although my system info _thinks_ it should be at `io.elementary.appcenter.desktop` but this doesn't seem to exist.

**Comment by DanielJoyce** [comment]
Pop shop dying for me too now. Just closes when I try and update installed deps. Really needs to be way more bulletproof.
