### ISSUE TITLE
Flathub link appears when there are no search results

### ISSUE THREAD

**Issue by leviport** [pop-os/shop#388]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
pop-shop:
  Installed: 3.4.2pop0~1659553725~22.04~cdc74cf
  Candidate: 3.4.2pop0~1659553725~22.04~cdc74cf
  Version table:
 *** 3.4.2pop0~1659553725~22.04~cdc74cf 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
When there are no search results, Shop informs me that I can sideload Flatpak apps, but provides a link to Flathub, which is a default configured Flatpak source in Pop:
![2022-09-15_09-02](https://user-images.githubusercontent.com/13512097/190439011-183f7d96-a9e1-4474-b314-b8af8e3eae1b.png)

Clicking the link takes me to the Flathub search results for the same search term, which don't contain what I was looking for, otherwise it would have appeared in Pop Shop.

**Steps to reproduce (if you know):**
Open Shop, search for something with no search results, like `trackmania`.

**Expected behavior:**
I'm not sure if the note about sideloading Flatpak apps is what we want in the first place, but it definitely isn't very helpful to have a link to Flathub, when Flathub is already a default Flatpak source in Pop.

**Other Notes:**

**Comment by isantop** [comment]
I think I agree about simply not showing any text about sideloading flatpak apps, since that isn't something we currently support without using the command line anyway
