### ISSUE TITLE
Seeing Search button instead of Back button in application window

### ISSUE THREAD

**Issue by Blinq-SanderBlom** [pop-os/shop#397]
**Distribution (run `cat /etc/os-release`):**
 `NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
`
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

`sander@pop-os ~> sudo apt policy pop-shop
pop-shop:
  Installed: 3.4.2pop0~1666654031~22.04~de9193e
  Candidate: 3.4.2pop0~1666654031~22.04~de9193e
  Version table:
 *** 3.4.2pop0~1666654031~22.04~de9193e 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
`

**Issue/Bug Description:**

In the top left corner you can see where the back button is supposed to be. It now looks like its renamed to search insted of back/return. The button work as expected but the naming is wrong 

![Screenshot from 2022-11-04 10-09-13](https://user-images.githubusercontent.com/110893407/199936154-3863dc2d-de98-47c9-ba36-f9c70e53773f.png)

**Steps to reproduce (if you know):**

Open the shop an click on any  application.

**Expected behavior:**

The button should say back?

**Other Notes:**

Had this issue for a while and I couldn't find any issues regarding this bug

**Comment by leviport** [comment]
Hmm, making the button say "back" might make sense, but I think a big part of this is because the arrow icon isn't showing up with the GTK theme you're using. With the default Pop theme, there's a left-facing arrow icon that kind of helps convey what that button does.

![shop](https://user-images.githubusercontent.com/13512097/200016044-df0a2c2c-dd60-4008-8b77-76e3c9396adf.png)
