### ISSUE TITLE
The new Pop Shop segfaults when it starts.

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/shop#402]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 22.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
`pop-shop 3.4.2pop0~1675897810~22.04~4194559`
(the latest commit from #401 )

**Issue/Bug Description:**
PopShop crashes when starting.
I started `io.elementry.appcenter` from the terminal to see why it crashes. Out of 40 tries, 8 of them crashed.

**Steps to reproduce (if you know):**
Start io.elementry.appcenter from the terminal. While it's loading keep changing the window size. Wait for it to load completely. Then close and try again. It will at some point crash.

One time it crashed because I was changing the window size while it was refreshing the database:
```
io.elementary.appcenter: ../../../../src/cairo-region.c:428: cairo_region_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&region->ref_count)' failed.
zsh: IOT instruction (core dumped)  io.elementary.appcenter
```
Once it crashed with:
```
malloc(): unaligned tcache chunk detected
zsh: IOT instruction (core dumped)  io.elementary.appcenter
```

The other 6 times it would not even show the window and only print this:
```
zsh: segmentation fault (core dumped)  io.elementary.appcenter

```

I couldn't find the exact place that it crashes but using gdb I found this:
```
Thread 13 "flatpak-worker" received signal SIGSEGV, Segmentation fault.
```

**Expected behavior:**

Not segfault.

**Comment by mmstick** [comment]
It's better to comment on #401 directly
