### ISSUE TITLE
This is still an issue well over a year later, with no update

### ISSUE THREAD

**Issue by CitizenPrayer** [pop-os/shop#409]
You can't tell me "we're working on it" and then actually not work on it. It's using nearly 1GB of my system's memory. This shouldn't be the case, yet it is, and several users have complained about it.

With all due respect (as this is what you requested), please actually fix this issue and not simply lock the post from discussion. Or, if you're not going to fix it, at least say so.

_Originally posted by @leviport in https://github.com/pop-os/shop/issues/257#issuecomment-1272044273_

**Comment by leviport** [comment]
[Yeah, we're actually working on it.](https://github.com/pop-os/shop/pull/401)

You could look at [open PRs on that repo](https://github.com/pop-os/shop/pulls) before accusing us of not working on it.
