### ISSUE TITLE
Pop!_Shop segfaults if we open any of the entries within categories within the app before recently updated and pop!_pics are loaded

### ISSUE THREAD

**Issue by ksatwar** [pop-os/shop#412]
**Distribution (run `cat /etc/os-release`):**
 "Pop!_OS 22.04 LTS"
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

io.elementary.appcenter

pop-shop:
  Installed: 3.4.2pop0~1666654031~22.04~de9193e
  Candidate: 3.4.2pop0~1666654031~22.04~de9193e
  Version table:
 *** 3.4.2pop0~1666654031~22.04~de9193e 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

When Pop!_Shop opens, the Pop!_Picks and Recently Updated section of the app takes a little while to load (around 10 seconds on my machine). However the Categories section is already ready for clicking. If we click on any sub-category ( Fun&Games/Graphics etc.) before Pop!_Picks and Recently Updated were loaded, it leads to a crash of the app after successfully opening the sub-category page.

If however we wait for Pop!_Picks and Recently Updated  to load fully before we go and click on any sub-category, it works fine and no crashes appear.

**Steps to reproduce (if you know):**

1. Open the Pop!_Shop application
2. click on any sub-category like graphics/audio etc. before Pop!_Picks and Recently Updated get a chance to load.
3. It will open the sub-category but will crash the application

**Expected behavior:**
No crashes when clicking on sub-category before the loading of Pop!_Picks and Recently Updated section of the app or the entire thing should load all at once. (all three sections) 

**Other Notes:**
I have attached the errors that appeared when i opened it through my terminal. I recreated this issue on two of my machines. Please let me know if I can provide any more details.
[pop!shop_crash.txt](https://github.com/pop-os/shop/files/12079418/pop.shop_crash.txt)

**Comment by jacobgkau** [comment]
The steps to reproduce no longer seem to crash the application on version 7.3.0 that was released last Wednesday. I'm closing the issue for now, but if you're able to recreate it again on the latest version, please leave a comment and we'll re-open it.
