### ISSUE TITLE
Keyboard shortcut for "Updates & Installed Software" doesn't work

### ISSUE THREAD

**Issue by silentTeee** [pop-os/shop#420]
I love the keyboard shortcuts that were added to the latest version of the Pop Shop! They were added to a hamburger menu list button in the top-right, which when opened shows the following entries:

![image](https://github.com/pop-os/shop/assets/20748060/ce7ca4ab-0f84-4e0e-a21a-d15e17a6ebe6)

Unfortunately, as the title says the "Updates & Installed Software" shortcut does not appear to function. Interestingly all the other keyboard shortcuts work as described, so I am not sure what happened with the "Updates" one...

**Comment by ziprasidone146939277** [comment]
Same here. Thank You for report.
