### ISSUE TITLE
Add API server for curated apps

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/shop#43]

**Comment by cassidyjames** [comment]
This is mostly web team, to spin up an API server that implements these endpoints: https://github.com/elementary/houston/blob/master/src/houston/controller/api/downloads.js @btkostner knows all about this. :wink: 

Then the desktop team would need to update the `HOUSTON_API_URL` const in the `AppCenterCore.Houston` class.

**Comment by btkostner** [comment]
This file actually: https://github.com/elementary/houston/blob/master/src/houston/controller/api/list.js. Looking at it, I think I might work on a v2 version of these API endpoints and clean up the naming. Then I can use phoenix and write a nice server for us, and eventually add a web UI to change them :shipit:

**Comment by cassidyjames** [comment]
This was implemented at https://github.com/pop-os/deckard
