### ISSUE TITLE
How do you submit apps?

### ISSUE THREAD

**Issue by elibroftw** [pop-os/shop#431]
Working on an app and we have an apt repository as well as deb files. How would we submit them to the pop shop? There's no links on this github repo.

**Comment by leviport** [comment]
The easiest way is probably to publish a Flatpak on [Flathub](https://flathub.org/). Deb packages come from from our Ubuntu mirror, so one would have to get their app added to Ubuntu upstream. We package a select few packages in our own Pop repos, but we try to keep the number of those pretty minimal.

**Comment by elibroftw** [comment]
Thanks for the quick response. Will look into it.
