### ISSUE TITLE
Add Pop! designed starting banner

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/shop#44]
Kate will be designing a banner for this. Cassidy and her will meet on Jan. 3 to discuss details and start planning.

**Comment by cassidyjames** [comment]
Rough notes from memory of that meeting:

- The elementary banner is styled like a clickable button (with the margins, gradient, strokes, and shadow like the categories buttons). If our banner is not clickable, it should **not** be styled in that way. We discussed doing a full-width hero sort of banner.
- We'll want to keep text relatively simple and on its own layer so it can be drawn by GTK, and translated appropriately.
- The elementary banner is around 300px tall, but that's flexible based on the design.

**Comment by isantop** [comment]
I'll add that including some extra fonts in Pop_OS greatly increases our ability to have visually stunning text in the header banner while retaining translatability.
