### ISSUE TITLE
Pop Shop display font hard to read

### ISSUE THREAD

**Issue by jbicha** [pop-os/shop#64]
**Reporter info**

```
 * Pop!_OS 18.04 Testing Build 12
 * pop-shop 0.2.8pop2~1521826576~18.04~c54035a
```
**Issue/Bug Description**

I opened Pop Shop, switched to the Installed tab and clicked Calendar.

The description and What's New fields are difficult to read. Specifically, the font size is somewhat small and it's not a good font choice for reading paragraphs. It's a font that I would expect to be used in headers where there isn't as much of a readability concern.

**Comment by brs17** [comment]
Thanks for pointing this out @jbicha 

The font does look a little small. I think downstream from elementary's appcenter we have been doing something slightly different(appcenter seems a lot easier to read). @isantop / @cassidyjames thoughts/opinions?

**Comment by cassidyjames** [comment]
@brs17 even using the elementary stylesheet with the same fonts and everything on Pop!_OS makes this a lot more readable. It looks like a stylesheet issue with a too-small default size for that widget, or something.
