### ISSUE TITLE
Pop Shop freezes when viewing page for AppStream addons

### ISSUE THREAD

**Issue by jbicha** [pop-os/shop#65]
**Reporter info**

```
 * Pop!_OS 18.04 Testing Build 12
 * pop-shop 0.2.8pop2~1521826576~18.04~c54035a
```
**Issue/Bug Description**

Open Pop Shop and switch to the Installed tab.

Click one of the Addons listed like _Gstreamer Multimedia Codecs_ or _Terminal Plugin for Files_

Pop Shop then takes 100% CPU and becomes unresponsive.

**Comment by jbicha** [comment]
It also affects the page for Firefox. (Due to a bug, Ubuntu's Firefox isn't showing appstream metadata at least in the GNOME Software app on Ubuntu.)

**Comment by brs17** [comment]
I was unable to recreate this issue on my machine with the latest version of 18.04. Are you still having this issue?

**Comment by OddSquirrel** [comment]
Confirmed after fresh Virtualbox install. Pop!_Shop freezes immediately after a package is selected. Instead of displaying the package details, the entire window becomes unresponsive and CPU is close to 100%.

`Pop!_Shop version: 0.2.9`

**Comment by karnophage** [comment]
I'm having similar issues on a fresh install. Attempting to install anything locks PopShop.

**Comment by brs17** [comment]
I have not been able to reproduce the issue following the instructions of: 
```
Open Pop Shop and switch to the Installed tab.

Click one of the Addons listed like Gstreamer Multimedia Codecs or Terminal Plugin for Files

Pop Shop then takes 100% CPU and becomes unresponsive.
```

More information is needed regarding what state the system must be in for this issue to occur.

Perhaps if someone could provide some logs when this happens? `journald -b` might show what is going on with the Pop!_Shop.

**Comment by mmstick** [comment]
This might be fixed by #95, possibly.

**Comment by brs17** [comment]
Huh, I don't know why I hadn't updated this, definitely have seen this issue.

**Comment by brs17** [comment]
Issue was fixed with https://github.com/pop-os/shop/pull/103
