### ISSUE TITLE
Shell search provider results are backwards

### ISSUE THREAD

**Issue by jackpot51** [pop-os/shop#7]

**Comment by sarahpandabeara** [comment]
Not really backwards, just un-ordered. Maybe makes sense to use alphabetical?

**Comment by WatchMkr** [comment]
They're actually backwards.

**Comment by jackpot51** [comment]
@WatchMkr  Nope! Search for VLC and the list will be:

YVFHL

Backwards would be:

YVLHF

If it was sorted, it would be:

FHLVY

**Comment by jackpot51** [comment]
I am going to sort them alphabetically

**Comment by WatchMkr** [comment]
How are they sorted now? Why is GIMP always at the bottom for a "GIMP" search and Inkscape always at the bottom for a "Inkscape" search?

I'm not certain alphabetical is the correct approach.

**Comment by jackpot51** [comment]
The sorting comes from AppStream.Pool.search. According to the documentation:

> Search for a list of components matching the search terms. The list will be ordered by match score.

AppCenter uses alphabetical sorting when you search from the top-right box.

**Comment by jackpot51** [comment]
I sorted in this commit: https://github.com/pop-os/shop/commit/e48e4955aae9909bc8e3cf7a97e07d22d4273e4b
