### ISSUE TITLE
Unable to update software sources via Pop Shop

### ISSUE THREAD

**Issue by enilsen16** [pop-os/shop#75]
**Reporter info**

```
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

```
pop-shop:
  Installed: 0.2.9~1524856680~18.04~7025a14
  Candidate: 0.2.9~1524856680~18.04~7025a14
  Version table:
 *** 0.2.9~1524856680~18.04~7025a14 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description**
```
Apr 28 15:31:08 pop-os io.elementary.appcenter-daemon.desktop[2175]: TypeError: Argument 0 does not allow None as a value
Apr 28 15:31:08 pop-os io.elementary.appcenter-daemon.desktop[2175]:     Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
Apr 28 15:31:08 pop-os io.elementary.appcenter-daemon.desktop[2175]:   File "/usr/lib/python3/dist-packages/repoman/main.py", line 54, in <module>
Apr 28 15:31:08 pop-os io.elementary.appcenter-daemon.desktop[2175]:     from repoman import main
Apr 28 15:31:08 pop-os io.elementary.appcenter-daemon.desktop[2175]:   File "/usr/bin/repoman", line 23, in <module>
Apr 28 15:31:08 pop-os io.elementary.appcenter-daemon.desktop[2175]: Traceback (most recent call last):
Apr 28 15:31:05 pop-os io.elementary.appcenter-daemon.desktop[2175]: Unable to init server: Could not connect: Connection refused
Apr 28 15:31:05 pop-os io.elementary.appcenter-daemon.desktop[2175]: No protocol specified
Apr 28 15:31:05 pop-os io.elementary.appcenter-daemon.desktop[2175]: Unable to init server: Could not connect: Connection refused
Apr 28 15:31:05 pop-os io.elementary.appcenter-daemon.desktop[2175]: No protocol specified
```

**Steps to reproduce (if you know)**
- Install Pop OS using the latest ISO
- Once installed, navigate to the pop shop and try to open the software sources settings. 

**Expected behavior**
- The settings open.

**Other Notes**
When I tried to do this in the live image I was able to open the settings. I tried deleting and reinstalling the pop shop and that didn't seem to help.

**Comment by enilsen16** [comment]
Closing because it seems to be related to https://github.com/pop-os/pop/issues/227

I switched to X11 and settings opened fine.

**Comment by Bananas-Are-Yellow** [comment]
Same here. I have experimented with logging in using Wayland. I have a new 15.6 inch System76 Oryx Pro with a 3840×2160 4K HiDPI display and graphics generally seem faster, especially animations. Only noticed two problems so far:

1. Resizing a Chromium or Firefox window produces thick black flickering bands on the right-hand side of the window. This turns out to be a [known issue](https://bugzilla.gnome.org/show_bug.cgi?id=767212) with XWayland clients.

1. Pressing the _Edit Software Sources..._ gear icon in Pop!_Shop does nothing. However, running `repoman` from the Terminal works fine.
