### ISSUE TITLE
French translation error when downloading packages upgrades without Internet connection

### ISSUE THREAD

**Issue by xolider** [pop-os/shop#76]
**Reporter info**

```
 * Distribution - Pop!_OS 18.04 LTS
 * Related Application and/or Package Version - pop-shop 0.2.9~1524856680~18.04~7025a14
```

**Issue/Bug Description**
The french translation might not be correct when a package upgrade is running and at the same time Internet disconnects.

**Steps to reproduce (if you know)**
run a package upgrade, and while the process is running, disconnect Internet connection (System langage have to be in French)

**Expected behavior**
Translation mistake

**Other Notes**
![capture d ecran de 2018-05-09 21-40-51](https://user-images.githubusercontent.com/7155896/39836271-18c0d59a-53d3-11e8-8440-fb4adc1d0f45.png)

**Comment by cassidyjames** [comment]
Looks like it's picking up the screenshot unavailable text. This could be because the translations don't line up or haven't been updated; I'm not entirely sure.

**Comment by xolider** [comment]
I don't know, this error happens when upgrading packages, so normally there should be no text related to a screenshot.

**Comment by brs17** [comment]
@cassidyjames @xolider looks like this issue happens upstream in appcenter as well, the following is a a screenshot from elementary OS:

![capture d ecran du 2018-05-09 17 42 14](https://user-images.githubusercontent.com/7460774/39846035-b853b0fe-53b6-11e8-820f-e2c2b0585a25.png)

So an issue should be created upstream here https://github.com/elementary/appcenter/. Right @cassidyjames ?

**Comment by cassidyjames** [comment]
@brs17 yep

**Comment by brs17** [comment]
Upstream bug created here: https://github.com/elementary/appcenter/issues/714

**Comment by xolider** [comment]
Bug resolved upstream !

**Comment by jackpot51** [comment]
We will merge the fix from Appcenter
