### ISSUE TITLE
Pop Shop updates won't go away.

### ISSUE THREAD

**Issue by Aphiso** [pop-os/shop#78]
My system is completely up to date, however the pop shop says I still have components to install. I've ran --full upgrade as well as pkcon refresh with no success.

![pop](https://user-images.githubusercontent.com/13264659/40963737-f3ebc0bc-686e-11e8-87f0-7daeca6f5a51.png)

uname -r outputs
```
@pop-os:~$ uname -r
4.15.0-23-generic
```

**Comment by mmstick** [comment]
Seems to be some sort of package conflict. I'm seeing it in a VM with a new install, where it wants to downgrade those packages (to the same version), but not on my system, which is an older install.

**Comment by mmstick** [comment]
Seems to be caused by the proposed PPA

**Comment by mmstick** [comment]
In the Pop!_Shop, click the gear image in the upper right of the header bar, then select `Developer Options`, and make sure the pre-release updates checkbox is unchecked. That will stop the notifications.

![screenshot from 2018-06-06 10-13-36](https://user-images.githubusercontent.com/4143535/41051063-4ee09d4a-6972-11e8-9fac-af3ededa488d.png)

**Comment by WatchMkr** [comment]
@mmstick since these packages have already been pushed to production, we should remove them from proposed.

**Comment by mmstick** [comment]
@WatchMkr Would have to ask Canonical to remove them.

**Comment by WatchMkr** [comment]
Oh, right. These are Ubuntu proposed.
