### ISSUE TITLE
Provide more information about updates

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/shop#79]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pop-shop:
  Installed: 0.2.9~1526005515~18.04~18df10f
  Candidate: 0.2.9~1526005515~18.04~18df10f
  Version table:
 *** 0.2.9~1526005515~18.04~18df10f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

The 'Software Updater' application from Ubuntu provides more detailed information about each update that it can apply.

![https://linuxconfig.org/images/04-update-ubuntu-packages-18.04-bionic.png](https://linuxconfig.org/images/04-update-ubuntu-packages-18.04-bionic.png)

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by twildeboer** [comment]
In addition, the Ubuntu "Software Updater" allows one to select which packages are actually upgraded (allowing the user to skip some). This is essential IMO.

**Comment by cassidyjames** [comment]
>In addition, the Ubuntu "Software Updater" allows one to select which packages are actually upgraded (allowing the user to skip some). This is essential IMO.

Pop!_Shop is designed to be fairly simple, and we wouldn't recommend users skip updates from their trusted software sources. I think if someone is looking for more granular control over specific updates, they can look into command line tools or apps like Synaptic. Regardless, I'd treat this as a separate issue from "providing more details."

**Comment by cassidyjames** [comment]
@ahoneybun which information specifically are you expecting, and how does that information help the user? I'm trying to understand the underlying want here.

**Comment by brs17** [comment]
After speaking with @ahoneybun he said he would like "changes and version numbers".

I know the version number is shown already. 

A link to a changelog might not be a terrible idea but I don't know how well it fits in with all of the other information currently provided.

**Comment by isantop** [comment]
Update changelogs are already provided for applications with AppStream support which provide their changelogs. Displaying the DEBIAN/changelog isn't a useful end-user feature, since that is usually quite a bit more verbose than would be necessary for most users.

**Comment by brs17** [comment]
Awesome, thanks for the insight @isantop . I am going to close this issue now as it seems like the desired information is already provided or not fitting for the Pop!_Shop.
