### ISSUE TITLE
No badge for updates

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/shop#85]
**Distribution (run `cat /etc/os-release`):** 
 
 ```
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
pop-shop:
  Installed: 0.2.9~1532969963~18.04~d2fb21b
  Candidate: 0.2.9~1532969963~18.04~d2fb21b
  Version table:
 *** 0.2.9~1532969963~18.04~d2fb21b 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

I no longer seem to be getting the update badge from Pop!_Shop on the "Installed" tab. The updates themselves are still listed on the "Installed" page itself, though.

**Steps to reproduce (if you know):**

1. Open Pop!_Shop with pending updates
2. See that there is no badge on the Installed tab
3. See that there are updates available in the Installed tab

**Expected behavior:**

A badge shows on the installed tab.

**Other Notes:**

I am experiencing this on a fresh and up-to-date install as of this morning. You can easily reproduce it with the fake update feature. elementary master also appears to work as expected in Pop!_OS.

**Comment by mmstick** [comment]
I found the problem, so there will be a fix in a minute.
