### ISSUE TITLE
Out of date Wesnoth

### ISSUE THREAD

**Issue by salamisalamis** [pop-os/shop#89]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by brs17** [comment]
Wesnoth is packaged by Debian as detailed on the Wesnoth wiki: https://wiki.wesnoth.org/WesnothBinariesLinux 

Therefore you will get the current Debian stretch version that is in the Pop!_Shop. 
https://packages.debian.org/search?keywords=wesnoth
