### ISSUE TITLE
Fix reverse-domain naming

### ISSUE THREAD

**Issue by jbicha** [pop-os/shop#9]
pop-shop uses `org.pop.shop` but that naming style is meant to correspond with a reverse domain name. But you don't own https://www.pop.org/

Something like `com.system76.pop.shop` is better.

**Comment by cassidyjames** [comment]
Ha, I came here to report this. It looks like this is not technically part of the spec, but a strong convention. I agree it would be better to use the RDNN of a domain we own. We initially had `org.pop-os.*` (we do own pop-os.org) but the dash caused issues with DBus.

**Comment by btkostner** [comment]
If we still wanted to use pop-os.org as the domain, the correct form would be `org.pop_os.*`

**Comment by jacobgkau** [comment]
`org.pop.shop` doesn't seem to be located anywhere in this repo anymore. The Pop!_Shop uses the upstream `io.elementary.appcenter` executable name, and has for some time. As such, I'm closing this issue for now.
